### PR TITLE
5.0 Diagrams update

### PR DESCRIPTION
**Pull request by bpoplauschi**
### New Pull Request Checklist

* [X] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [X] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [X] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [X] I have updated this branch with the latest 5.x to avoid conflicts (via merge from master or rebase)

This merge request fixes / reffers to the following issues: #2285 

### Pull Request Description
Updated the StarUML diagrams + added a High Level Diagram (thanks to @dreampiggy)

### CODE REVIEW

**Comment by bpoplauschi** [comment]
@dreampiggy please review and merge. I thought the diagram you created was very good for a high level overview of our architecture, so I added it as well.
I mean this one

**Comment by bpoplauschi** [comment]
Here are the new diagrams (so it's easy for the review):
### Class Diagram

### Sequence Diagram

**Comment by bpoplauschi** [comment]
CC @zhongwuzw @mythodeia @skyline75489

**Comment by dreampiggy** [comment]
LGTM

**Comment by bpoplauschi** [comment]
Actually, from the one big class diagram, created several smaller ones:
- still one overall class diagram, but that doesn't list any attributes, methods
- dedicated diagrams for each section (containing a bigger level of detail)
  - top level API (WebCache categories, Prefetcher, Manager)
  - manager
  - coders
  - loader
  - cache

Created a Docs/Diagrams folder.

## showcase of README
#### High Level Diagram
<p align="center" >
    
</p>

#### Overall Class Diagram
<p align="center" >
    
</p>

#### Top Level API Diagram
<p align="center" >
    
</p>

#### Main Sequence Diagram
<p align="center" >
    
</p>

#### More detailed diagrams
- [Manager API Diagram](https://github.com/bpoplauschi/SDWebImage/blob/diagrams/Docs/Diagrams/SDWebImageManagerClassDiagram.png?raw=true)
- [Coders API Diagram](https://github.com/bpoplauschi/SDWebImage/blob/diagrams/Docs/Diagrams/SDWebImageCodersClassDiagram.png?raw=true)
- [Loader API Diagram](https://github.com/bpoplauschi/SDWebImage/blob/diagrams/Docs/Diagrams/SDWebImageLoaderClassDiagram.png?raw=true)
- [Cache API Diagram](https://github.com/bpoplauschi/SDWebImage/blob/diagrams/Docs/Diagrams/SDWebImageCacheClassDiagram.png?raw=true)

## The more detailed diagrams
#### Manager API Diagram
<p align="center" >
    
</p>

#### Coders API Diagram
<p align="center" >
    
</p>

#### Loader API Diagram
<p align="center" >
    
</p>

#### Cache API Diagram
<p align="center" >
    
</p>

**Comment by bpoplauschi** [comment]
I'm merging (was approved).

**Pull request merged**
