### PR TITLE
Use NSURLComponents to get cached file name rightly. Fix for issue #1758

### PR DESCRIPTION
**Pull request by eggswift**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have added the required tests to prove the fix/feature I am adding
* [x] I have updated the documentation (if necesarry)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / reffers to the following issues: #1758

### CODE REVIEW

**Comment by eggswift** [comment]
@bpoplauschi
@mythodeia
@harishkashyap

Please take a look. Thanks

Cheers

**Comment by eggswift** [comment]
@bpoplauschi
@mythodeia
@harishkashyap

Please take a look. Thanks

**Comment by bpoplauschi** [comment]
@eggswift thanks for working on this, but I can't merge it yet.
Let me tell you why. We had some previous issues in this area of the project (name of the file saved to disk):
- in 3.8.0 we wanted to fix an issue (file name contained the URL query) so we: 
  - Removed the URL query params from the filename (key) fb0cdb6 1bf62d4 #1584 - fixes #1433 #1553 #1583 #1585
- in 3.8.1 we had to revert because of 
  - SDWebImage 3.8.0 get wrong image #1589 - the issue was caused by the changes in 3.8.0 (Removed the URL query params from the filename (key) fb0cdb6 1bf62d4 #1584 - fixes #1433 #1553 #1583 #1585) - Reverted.
  - Note: The solution for those issues (i.e. #1433 #1553) is to set the SDWebImageManager cacheKeyFilter block and do their own calculations there.

We need to have a thorough look at the whole case and see if we can do the change you want.

**Comment by eggswift** [comment]
@bpoplauschi  It seems to be a thorny issue , thanks!

**Comment by bpoplauschi** [comment]
I have re-reviewed this issue. I don't think we can merge your fix, or we will do the same mistake I described before. Feel free to add this way of computing the key using `cacheKeyFilter`.
Sorry about this, but I think it's better this way for the majority of the users and who needs to override it, can do it.

**Pull request closed without merging**
