### PR TITLE
Google removed this Repo, updating it to the real one

### PR DESCRIPTION
**Pull request by seanscal**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have added the required tests to prove the fix/feature I am adding
* [x] I have updated the documentation (if necessary)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / reffers to the following issues: ...

### Pull Request Description

...

### CODE REVIEW

**Comment by evliu** [comment]
Hoping for this to get merged soon; it fixes this https://github.com/rs/SDWebImage/issues/1882 , which I need for a carthage install

**Comment by bharath2020** [comment]
Same here, we are currently blocked by this issue. Hopefully, we can get this merged soon.

**Comment by mythodeia** [comment]
the mirror works fine https://github.com/webmproject/libwebp
are you still having issue?

**Comment by evliu** [comment]
Looks like they fixed it. It was an empty repo while the issue was up

**Comment by bpoplauschi** [comment]
Let's close this PR and revisit later.
Thanks for the involvement @seanscal @evliu

**Pull request closed without merging**
