### PR TITLE
Move webp component (and libwebp dependency) to SDWebImage/SDWebImageWebPCoder

### PR DESCRIPTION
**Pull request by bpoplauschi**
### New Pull Request Checklist

* [X] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [X] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [X] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [X] I have updated this branch with the latest 5.x to avoid conflicts
* [X] I have updated the documentation (if necessary)
* [X] I have run the tests and they pass
* [X] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / refers to the following issues: #2078 
Similar to #2385 (which does the same thing for `FLAnimatedImage` integration and our `gif` component)

### Pull Request Description
- move the `webp` component + the `libwebp` dependency to [SDWebImage/SDWebImageWebPCoder](https://github.com/SDWebImage/SDWebImageWebPCoder)
- Xcode 9.4

### CODE REVIEW

**Comment by bpoplauschi** [comment]
Keeping the `DO_NOT_MERGE` label until review is done and we move the tests/demo to the dedicated project.

**Comment by dreampiggy** [comment]
So we also remove the `demo` usage of static/animated WebP images ? Could we keep the demo Podfile with `SDWebImageWebPCoder` and continue to use that instead ?

I guess that WebP images, use more widely than any other coder plugins format like APNG/BPG/HEIF. So maybe we can make the demo to show the WebP coder as well.

**Comment by dreampiggy** [comment]
@bpoplauschi Is that hard to run the demo with `SDWebImageWebPCoder` ? If so, we can just remove all WebP images in the demo. Just reference the link to that `WebP` project and provide a demo as well.

This may because I sometimes use our project demo to profile the `UIImageView` && `SDAnimatedImageView` rendering performance. Since WebP supports `SDAnimatedImageCoder` protocol, it should be checked as well (Now I need to run two demos at the same time). Anyway, put into different repos is OK.

**Comment by bpoplauschi** [comment]
@dreampiggy It was not that difficult, just a few travis CI changes were needed.
I think I managed to do most of the stuff I wanted on this PR. Ready for review/merge

**Pull request merged**
