### PR TITLE
Remove locks in SDAnimatedImageView

### PR DESCRIPTION
**Pull request by zhongwuzw**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [ ] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [ ] I have added the required tests to prove the fix/feature I am adding
* [ ] I have updated the documentation (if necessary)
* [ ] I have run the tests and they pass
* [ ] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / reffers to the following issues: ...

### Pull Request Description

Totally remove locks in `SDAnimatedImageView`. Currently we use lock to prevent thread race condition when operate `frameBuffer`. TBO, we can remove all these locks. We can see where we operate `frameBuffer` :

- `resetAnimatedImage`, be called in `setImage`, so it would be called on main thread. (`setImage` is `UIKit` API, should call on main thread).
- `setImage`, the same as above, should be called on main thread.
- `didReceiveMemoryWarning`, be called on main thread.
- `displayDidRefresh`, also be called on main thread.

So, the only place would produce race condition is when we prefetch frame in `fetchQueue`, but it's easy to fix, just use `GCD` to keep safe like below:

```
        NSOperation *operation = [NSBlockOperation blockOperationWithBlock:^{
            UIImage *frame = [animatedImage animatedImageFrameAtIndex:fetchFrameIndex];
            dispatch_async(dispatch_get_main_queue(), ^{
                self.frameBuffer[@(fetchFrameIndex)] = frame;
            });
        }];
```

### CODE REVIEW

**Comment by dreampiggy** [comment]
Need some time to consider this issue. This not something only about thread-safe. It's about the animation rendering.

Why to use lock instead of GCD to dispatch, it's because lock can actually `block` main queue immediatelly until the fetch queue write the frame into the cache.

Consider this case : Current rendering frame is `0`, and when next frame duration is reached, we need to render the `1` frame as fast as possible. Assume the thread-safe condition is reached (Query cache in main queue but fetchQueue was writing the `1` frame).

When using block, we will block main queue and let `1` frame sucessfully write to cache, then main queue get the `1` frame and render it.

However, if we use GCD to dispatch fetchQueue into main queue, the `1` frame will not be in the cache, so that `1` frame will be trigged as a cache miss. This time will not render the `1` frame. Even worse, this simple change of code will cause a issue that we re-fetch the `1` frame (Because the `fetchFrame` is also nil and start fetch `1` frame again)

So this need detailed consideration. I'll check it back later.

**Comment by zhongwuzw** [comment]
@dreampiggy 👌 

> When using block, we will block main queue and let 1 frame sucessfully write to cache, then main queue will be resumed, and get the 1 frame and render it.

🤔 Emm, have no idea where it would block to wait to cache? 

> Even worse, this simple change of code will cause a issue that we re-fetch the 1 frame (Because at this time, the fetchFrame is also nil and start fetch 1 frame again)

I think no re-fetch would be appear? `fetchQueue` only support one operation to run. [`self.fetchQueue.operationCount == 0`](https://github.com/rs/SDWebImage/pull/2473/files#diff-9cdf661490007a0fb3566a2760b9597dL749)


> However, if we use GCD to dispatch fetchQueue into main queue, the 1 frame will not be in the cache until next runloop.

Change `dispatch_async(dispatch_get_main_queue()` to `dispatch_sync(dispatch_get_main_queue()`, I think it maybe the same as the original code.

**Comment by dreampiggy** [comment]
@zhongwuzw > Emm, have no idea where it would block to wait to cache?
Because whether we decide to query the `fetchFrame`, is dependent on `whether current frame is available just in time`. So if we simply remove the LOCK and use GCD to write the frame cache, then we actually query the frame finished, we need to wait all of main queue job finished and write it into frame cache in the next runloop. It's late.

> I think no re-fetch would be appear? fetchQueue only support one operation to run. 
The fetch queue is just a operation queue. Why the code add `operationCount == 0` because it base on the assumation that we can write to the cache in time. No need to query multiple frames. But however, using GCD to wait for main queue be operated, will make this assume failed. If we need to change it, we can do another solution, such as allow multiple query frame at the same time, but in the operation block add index guard to avoid different operation share the same index. But this need some more code to do.

> Change dispatch_async(dispatch_get_main_queue() to dispatch_sync(dispatch_get_main_queue(), I think it maybe the same as the original code.
Actually this does not. Because `dispatch_sync` still need to submit your code into the last of main queue and wait for main queue to execute all previous code until this block been done. You just can ensure it blocks the operaion queue. However, when using `block`, the code will immediatelly (nearlly, actually) be executed, don't need to wait for main queue waiting code to be executed. So there are some little difference.

**Comment by zhongwuzw** [comment]
@dreampiggy 
> The fetch queue is just a operation queue. Why the code add operationCount == 0 because it base on the assumation that we can write to the cache in time, so one frame render, one check, one query is enough.

Nope, we can't do this assume, mostly, it would not in time. Let's assume most devices have 2 core, so only 2 jobs would be run at the same time, main thread, system, users, would do many works, most of the time, more than 2 threads, so thread context switch would not be prevented. `NSOperationQueue`'s default priority is `NSOperationQualityOfServiceBackground`, priority is slow.

> Actually this does not. Because dispatch_sync still need to submit your block code into the last of main queue and wait for main queue to execute all previous code until this block been done. Sync just ensure it blocks the operaion queue so that the operation is not been marked finished. However, when using block, it will interrupt the running main queue (what GCD can not) 

TBO, I don't get what you want to express. I don't know wether you mess up the runloop, runloop is just a `do while`, a event loop, if no message, it sleep, when message becomes, it wake up and handle it, `DisplayLink` is just a timer, the interval it 1/60s, it added to runloop, so every 1/60s, runloop would handle it. So if we add block to main queue, no matter how many it is, if runloop is sleep, it would wake up the runloop, runloop would call all blocks one by one added before by `__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__`. 

> the following pair dispatch_semaphore_wait dispatch_semaphore_signal call does not cause performance lost. It just increase/decrease the semaphore count. Only when thread-safe race condition is apperared can block the calling queue. 

Emm, 8 days ago, you said it would be the cost, see [comment you leave](https://github.com/rs/SDWebImage/pull/2468#issuecomment-417629492). And not you said, cost is always exist, no matter wether or not thread-safe race condition, it would do atomic operation.

lock_benchmark


> GCD will make a queue switch each time you access. And GCD's thread pool is limited to 64 on iOS. No need this extra cost.

Maybe you mean thread switch? thread switch is always exist, `sync` is just add a block to main queue.
`GCD`'s thread pool is limited to 64, it's correct, and also what I want to say in [Add autoreleasepool to release autorelease objects in advance when using GCD](https://github.com/rs/SDWebImage/pull/2474#issuecomment-419399832), in that `PR`, we can't do one operation to one queue. because one queue may spawn a new thread, so it's easy to make app hang, mean thread explosion, because user may use a number of threads, our framework also may use many threads, I don't remember which `WWDC` session, `Apple` developer give some demos how to use `GCD` and decode image, you can check it.


And, maybe this `PR` needs more people to review IMO, @bpoplauschi @skyline75489 @mythodeia .
I also would  check the `SDAnimatedImageView` to figure out wether it has any issue.

**Comment by dreampiggy** [comment]
And for these two approaches. Today I try to run profile about these two approach. For most of cases, they behave some on performance. The lock there does not cause issue.

However, during the test, use simple GCD queue using the cid: aeca363ef169c5a5a5cb1bc0ab86bcf01184b12b, have a race ratio that can query the same frame index twice, even the memory is enough for full buffer. However, using lock does not contains this issue.




The demo I use, which contains the different test between `SDAnimatedImageView` && `SDAnimatedImageView(With this PR's NO LOCK patch) && YYAnimatedImageView`). You can try to run it as well. (run `pod install` after download, and you can also modify the `SDImageGIFCoder` code to check that assert)

[SDWebImageTest.zip](https://github.com/rs/SDWebImage/files/2363216/SDWebImageTest.zip)


Remove lock is OK. But I think, we should ensure this not cause some extra issue.


PS: Actually I don't want to spend more on it. If you can ensure this is OK, we can merge it now actually. Me && @bpoplauschi are hurried for 5.0.0 official release. I'm spending time to update documentation and tests, and check if there are anything important API break thing to do. Since this is a performance enhancement PR so we can also fix it in the furture (No API break). So maybe I'll put it into a low priority.

**Comment by bpoplauschi** [comment]
Guys, here is my opinion:
- this improvement does not come based on a real problem found by our users or us
- I would love to get rid of the locks, but it seems (at least to me) we do need them for safety
- the improvements would be smalls
- this case if different from the one we discussed about autoreleasepools, since that was based on actual measurements and with big impact
- I simply suggest we don't merge this PR
- @zhongwuzw hope you keep putting up PRs :) you're doing great. Just that some of them might not be merged. Same for everyone here.

**Comment by zhongwuzw** [comment]
@bpoplauschi 👌 I'll be go on to do some fixes. 😂 ❤️ 

@dreampiggy I'm ok for this `PR` merge or not merge, no matter for me.
I see your `ThreadSafeTest` demo, it compares many locks performance, but for this situation, I want to do is free the main thread, because nearly all methods called on main thread, no need to use lock in these methods.

For the issue, I want to tell you, it's the issue of code reorder and thread context switch, not the issue of `GCD`.

Locks also has this issue.
image
image

**Pull request closed without merging**
