### PR TITLE
Bugfix webp encode color mode

### PR DESCRIPTION
**Pull request by dreampiggy**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have added the required tests to prove the fix/feature I am adding
* [x] I have updated the documentation (if necessary)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / reffers to the following issues: ...

### Pull Request Description

There seems a bug in the **WebP Encoding** ...

Which `SDWebImageCoder` encoding always assume the input `CGImage` is RGBA8888 color mode. See the [code here](https://github.com/rs/SDWebImage/blob/5.x/SDWebImage/WebP/SDImageWebPCoder.m#L505-L509). And if you don't know what color mode is, it's the layout order of R/G/B/A pixel. See [Apple-Color Spaces and Bitmap Layout](https://developer.apple.com/library/content/documentation/GraphicsImaging/Conceptual/drawingwithquartz2d/dq_images/dq_images.html#//apple_ref/doc/uid/TP30001066-CH212-CJBHEGIB)

This will cause, for example, input `BGRA8888` image encode a wrong WebP image data, which mass up RGB color channel. This code seems original from me, but at that time I didn't realize this bug because the WebP decoding always output `RGBA8888`, which the same as encoding color mode we assume... 😓 

For example, see the test image which is a `BGRA8888` color mode, and the output webp image data's preview image (Which wrongly treat `BGRA8888` as `RGBA8888`)

> TestImageStatic.webp
inputimage_2 tiff

> Output webp data's preview image
outputimage_3 tiff

I find that 4.x contains this bug as well...So maybe I need to create a PR in master branch and merge in 5.x ?

### CODE REVIEW

**Comment by dreampiggy** [comment]
I guess I need to create a PR for 4.x master branch as well ? (Or fix for 4.x master branch first, they merge to 5.x). 😓

**Comment by dreampiggy** [comment]
😅 Anyone who can review this change ? @bpoplauschi @mythodeia . If available, I can also merge this into 4.x because no API changes and it's a bug...

**Comment by bpoplauschi** [comment]
@dreampiggy I tried to change the base branch to `master` and merge it there first, but it doesn't work (too many differences). This needs to be propagated to the `master` branch as well.

**Comment by dreampiggy** [comment]
@bpoplauschi I'll create a MR later...:)

**Pull request merged**
