### PR TITLE
watchOS and OSX support (One platform to rule them all)

### PR DESCRIPTION
**Pull request by bpoplauschi**
* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [ ] I have added the required tests to prove the fix/feature I am adding
* [ ] I have updated the documentation (if necessary)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

This merge fixes: #1346 and #1192 by adding **watchOS** support.  It also resolves #698 by adding **OSX** support.

### Pull Request Description

- Clarified and simplified the usage of `TARGET_OS_*` macros. Added `SD_MAC`, `SD_UIKIT`, `SD_IOS`, `SD_TV`, `SD_WATCH`. The biggest issue here was `TARGET_OS_MAC` was 1 for all platforms and we couldn't rely on it.
- the `SDWebImage xcodeproj` contains the following targets:
  - `SDWebImage iOS static` (iOS static lib)
  - `SDWebImage watchOS static` (watchOS static lib)
  - `SDWebImage OSX` (OSX dynamic framework)
  - `SDWebImage iOS` (iOS dynamic framework)
  - `SDWebImage tvOS` (tvOS dynamic framework)
  - `SDWebImage watchOS` (watchOS dynamic framework)
- the `SDWebImage Demo xcodeproj` contains the following targets:
  - `SDWebImage OSX Demo`
  - `SDWebImage iOS Demo`
  - `SDWebImage TV Demo`
  - `SDWebImage Watch Demo`
- switched Travis to Xcode 7.3 images

### CODE REVIEW

**Comment by bpoplauschi** [comment]
@mythodeia please take a look

**Comment by mythodeia** [comment]
getting it now

**Comment by mythodeia** [comment]
building the IOS demo on the simulator works fine. when i build for the device i get this 3 errors:
``` GNU-style inline assembly is disabled``` in the enc_neon.c file
screen

**Comment by bpoplauschi** [comment]
@mythodeia good catch. It seems it's an issue with building the webp files for watchOS - device. Because they compile fine for iOS device. I will look into it.

**Comment by bpoplauschi** [comment]
@mythodeia here's the more detailed issue:
- inline assembly is incompatible with ios and watchos
- because of the ios part, the google folks added this code
```
// Right now, some intrinsics functions seem slower, so we disable them
// everywhere except aarch64 where the inline assembly is incompatible.
#if defined(__aarch64__)
#define WEBP_USE_INTRINSICS   // use intrinsics when possible
```
Then if `WEBP_USE_INTRINSICS` is defined, the assembly inline code is replaced by some other code (which is probably slower), but can compile.
- so for the ios, it will define WEBP_USE_INTRINSICS, but for watchos it wont'.
- even if we get it to work in our project, if someone uses it with CocoaPods, I'm not sure if we could force define `WEBP_USE_INTRINSICS`

**Comment by bpoplauschi** [comment]
@mythodeia I added a new commit that sets `WEBP_USE_INTRINSICS` for the watchOS targets, it builds fine now. Probably we will need to define this in our podspec so people don't need to set it manually.

**Comment by mythodeia** [comment]
it works fine now on device apart from this:
issue 
which is easily fixed by changing the build number from 1.0 to 1 on SDWebImage iOS Demo target  

However i am getting this for the simulator:
screen

**Comment by bpoplauschi** [comment]
Good catches. I actually missed 2 files from the new webp. Travis also showed this error. Should be fixed now.

**Comment by mythodeia** [comment]
@bpoplauschi everything builds just fine now. I will test it a bit more tomorrow

**Comment by bpoplauschi** [comment]
@mythodeia I will also merge this in. let me know if you managed to test anything

**Pull request merged**
