### PR TITLE
fix BUG:https://github.com/rs/SDWebImage/issues/1484

### PR DESCRIPTION
**Pull request by LululuSir**
### New Pull Request Checklist

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [ ] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [ ] I have added the required tests to prove the fix/feature I am adding
* [ ] I have updated the documentation (if necessary)
* [ ] I have run the tests and they pass
* [ ] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / reffers to the following issues: ...

### Pull Request Description

...

### CODE REVIEW

**Comment by bpoplauschi** [comment]
@LululuSir thanks for submitting the PR, but please detail a bit:
- why do you think this is the proper fix for the issue #1484 
- how did you test? can you write some unit test?

**Comment by LululuSir** [comment]
Reiteration path:
       Decompress the same image in multi-thread at the same time.
       One way to increase the probability of crash , is to decompress an animated image(gif/apng).

Reason(Speculation):
      This function is not thread safe:
      CGContextDrawImage(CGContextRef c, CGRect rect, CGImageRef image);

Verification:
      It was very easy to crash when decompress the same imageRef in two thread at the same time. And it was fixed when I add the thread protection.

**Comment by bpoplauschi** [comment]
@LululuSir thanks for the details. Could you also add a unit test?
@dreampiggy what do you think? It sounds valid to me

**Comment by dreampiggy** [comment]
@LululuSir What about using a atomic immutable array for normal method, and only `addCoder:` & `removeCoder:` create a new mutable coders instead ? That `mutableCoders` design looks a little tricky and keep a dispatch queue for thread-safe is overcome...


```objective-c
// Interface
/**
 All coders in coders manager. The coders array is a priority queue, which means the later added coder will have the highest priority
 */
@property (atomic, copy, readwrite, nullable) NSArray<id<SDWebImageCoder>> *coders;

// Implementation
- (void)addCoder:(id<SDWebImageCoder>)coder {
    if (![coder conformsToProtocol:@protocol(SDWebImageCoder)]) {
        return;
    }
    NSMutableArray<id<SDWebImageCoder>> *mutablecoders = [self.coders mutableCopy];
    if (!mutablecoders) {
        mutablecoders = [NSMutableArray array];
    }
    [mutablecoders addObject:coder];
    self.coders = [mutablecoders copy];
}

- (void)removeCoder:(id<SDWebImageCoder>)coder {
    if (![coder conformsToProtocol:@protocol(SDWebImageCoder)]) {
        return;
    }
    NSMutableArray<id<SDWebImageCoder>> *mutablecoders = [self.coders mutableCopy];
    [mutablecoders removeObject:coder];
    self.coders = [mutablecoders copy];
}
```

**Comment by LululuSir** [comment]
@dreampiggy I think it will work too.
@bpoplauschi I find it in product environment, and it fix that crash.But, I can't reiteration in a demo or unit test

**Comment by bpoplauschi** [comment]
Got it. I like @dreampiggy's suggestion

**Comment by dreampiggy** [comment]
@bpoplauschi @LululuSir 😅 Well. I miss one thing. Just mark `coders` as `atomic` may non-thread safe in this case.
If two thread call `addCoder:` with two different coders. There may be a posibility that each of two threads get the original coder array, and they both modify to add one. The final result will contains only  one of the desired added coder.

```objective-c
// Time begin

<--- Thread 2 here
NSMutableArray<id<SDWebImageCoder>> *mutablecoders = [self.coders mutableCopy];
if (!mutablecoders) {
    mutablecoders = [NSMutableArray array];
}
<--- Thread 1 here
[mutablecoders addObject:coder];

// Time passe

<--- Thread 2 here, mutable coders is nil, then it create empty array @[]
if (!mutablecoders) {
    mutablecoders = [NSMutableArray array];
}
[mutablecoders addObject:coder];
self.coders = [mutablecoders copy];
<--- Thread 1 here, the coders is @[coder1]

// Time passe

self.coders = [mutablecoders copy];
<--- Thread 2 here, the coders is @[coder2]
```

So actually, we need a lock to guard this instead of using `atomic`. I can create a PR for this.

**Comment by bpoplauschi** [comment]
@dreampiggy you are correct, we need to lock the part where we edit the array. That is a common pattern, which we have used to do with a serial queue that is the recommended method from Apple to synchronising access to a non-thread safe resource. We can also use a lock. But you are right, we can't just rely on the `atomic` flag.

**Comment by dreampiggy** [comment]
I'll provide a fix in 4.x.

This `decompressedImageWithImage:data:options` is totally removed in 5.x because the fact that `force decode` a image is not related to `image format`, so it's not part of custom coder to provide a implementation. Instead, we use `SDWebImageCoderHelper` to do this force decode process. It's thread-safe.

**Comment by dreampiggy** [comment]
@LululuSir See #2274

**Comment by dreampiggy** [comment]
Done by #2274....Which use a lock to guard thread-safe for this coders manager.

**Pull request closed without merging**
