### PR TITLE
Determines at runtime is UIApplication is available as per #1082

### PR DESCRIPTION
**Pull request by flovilmart**

### CODE REVIEW

**Comment by bassrock** [comment]
:+1: But also suggest lowering the deployment target to 8.0 on the framework.

**Comment by bassrock** [comment]
:+1:

**Comment by auibrian** [comment]
On 8.2 at least it is possible to call `[UIApplication sharedApplication]` inside an extension so these checks will pass when used in an extension. The net result is tricking the compiler into letting you use non-extension safe API which will pass app review (possibly) but could still lead to instability during use.

**Comment by flovilmart** [comment]
Yeah, that's exactly the purpose. But why would it lead to instability 'during use'? Do you have examples? We have one extension going to review and live as we speak. We're waiting to hear back from it.

**Comment by auibrian** [comment]
- A call to `applicationDelegate` will return `nil`
- How `openURL` is meant to work inside an extension is undefined

`NS_EXTENSION_UNAVAILABLE` was presumably created for a reason, and given that `[UIApplication sharedApplication]` actually works inside of an extension the assumption is that there were problems there that Apple didn't want to address right now so they made it a compile time error.

**Comment by flovilmart** [comment]
What’s your point here?

**Comment by auibrian** [comment]
My point is that your runtime check for availability of UIApplication sharedApplication will always return true. We don’t know why Apple designated the API unsafe so your change means that we are now using API considered unsafe in our extension.

**Comment by auibrian** [comment]
More specific to this exact commit:
* what happens when an extension starts a background task?
- and then the extension is killed?

I don't know the answers to these questions, I could speculate, but I have no concrete knowledge. So for the sake of having a singular build target (which I agree is preferable) we're introducing an unknown quantity into our extensions and we're having to fake out the compiler to do so.

**Comment by flovilmart** [comment]
Extensions can’t start background tasks through sharedApplication, as it’s not available.

We all agree a single build target is the way to go, so all sanity checks have to be performed at runtime. You’re welcome to explore the issue :)

I believe the current tests showed a proper behaviour on the simulator. As it wasn’t impossible to test on real devices, that was our best shot to get a fellow use to get his extension in review. We’ll see how the submission go and it will be easy to refactor/improve the code once we can confirm/infirm the workaround is properly designed.

**Comment by auibrian** [comment]
That's actually what I have been trying to convey: I have explored it further, and they can start background tasks because sharedApplication is available. Here is proof: https://github.com/auibrian/SafeExtension

The runtime checks do nothing, they always pass. That's my entire point.

Further, from past experience again: Apple don't seem to be checking overly hard for this, because even without using performSelector I've had an app approved where I unintentionally used sharedApplication from an extension. (You can work around the check by changing where/what you link etc) So I won't be surprised at all if the app is accepted but it will mean nothing.

**Comment by flovilmart** [comment]
So what's your solution?

**Comment by bassrock** [comment]
Chime in here. Quick update on my app review. There was a legal thing I had to fix on my app, but after an appeal its still "In Review" so we will see where it goes.

**Comment by bassrock** [comment]
AND APPROVED :+1:

**Comment by flovilmart** [comment]
Alright!

**Comment by bassrock** [comment]
Processing for the store right now but once its available: https://itunes.apple.com/us/app/disney-wait-times/id963982614?ls=1&mt=8

Its (hopefully) the first DisneyLand Wait Time app for the Watch.

**Comment by flovilmart** [comment]
Good job man! Glad we could help!

**Comment by auibrian** [comment]
As I said, this isn't a surprise. I already had an app approved that uses extension unsafe API. That doesn't mean you should do it, that's the entire problem with this PR.

**Comment by flovilmart** [comment]
So what's the alternative?

**Comment by bassrock** [comment]
@auibrian would be helpful if you could provide a solution

**Comment by flovilmart** [comment]
Yeah... The goal is that the community don't wonder about compiler warnings, Carthage builds properly, the framework works in all environment and that the framework don't lead to App Store rejection.

So far all of the above are OK. You're welcome to superseed the solution, and PR.

**Comment by auibrian** [comment]
PR'd in November: https://github.com/rs/SDWebImage/pull/953

I also can't tell if you are being purposely obtuse: You are purposely circumventing a compiler warning in order to only have to compile something once, and in the process you are doing exactly what Apple have requested you not do: access sharedApplication. I've proven to you that the code WILL run in an extension and that your runtime check is not actually doing anything but your only concern is whether it passes app review. I don't think the community prefers potentially unsafe code to compiler warnings. Whether or not you made it past app review this is not a PR that should be accepted.

**Comment by flovilmart** [comment]
You're not giving answers. Your solution imposes a preprocessor macro, that leads to incompatibility with Carthage. Therefore, yours should not be accepted either. I'm open to solutions. I'm not blaming you on your PR that you're not Carthage compatible. So please, either be constructive, or let the maintainers decide wether it should be accepted or not. And tested in extensions, the behavior is fine, doesn't lead to instability or crash. provide some code that will force crash the extension or app. We'll refine the solution. I guess we can detect with another runtime attribute, property, class that we're running into an extension.

**Comment by flovilmart** [comment]
The problem is plain simple:

1. Single framework

2. No warnings

3. Extension and watch kit safe, at runtime and review 




You're welcome to come with a solution that solves all the above

**Comment by appsforall** [comment]
Any plans on when this will be added? As AppBoy has a direct dependency to SdWebImage, we are forced to stay behind on a buggy cocoa pods version as SDWebImage cannot build for extensions. Would be great to hear from you!

**Comment by bassrock** [comment]
@rs Any chance of this getting merged?

**Comment by auibrian** [comment]
Suggesting this: https://github.com/rs/SDWebImage/pull/1182 as a replacement to this recently merged issue.

**Pull request merged**
