### PR TITLE
Fixes for issues #821 and #1305

### PR DESCRIPTION
**Pull request by iosnatarajan**
### New Pull Request Checklist
- [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
- [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
- [ ] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none
- [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
- [x] I have added the required tests to prove the fix/feature I am adding
- [x] I have updated the documentation (if necesarry)
- [x] I have run the tests and they pass
- [ ] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / reffers to the following issues: ...
### Pull Request Description

...

Resolved the image Cache issues by comparing the modified date.

### CODE REVIEW

**Comment by iosnatarajan** [comment]
Resolved the image Cache issues #821 and #1305.

**Comment by iosnatarajan** [comment]
Resolved the image Cache issues #821 and #1305.

**Comment by bpoplauschi** [comment]
@iosnatarajan looks very interesting. We will need a thorough review, but this is promising.

**Comment by iosnatarajan** [comment]
@bpoplauschi How long will it take to merge this pull request?

Thanks!

**Comment by bpoplauschi** [comment]
@iosnatarajan not sure, there are a bunch of items pilled up for 4.0, I'm moving through them.

**Comment by MoridinBG** [comment]
I tried this fork, as I needed a cache aware way to fetch large images, that may change behind a static URL.
I am using the sd_setImageWithURL method on UIImageView with the RefreshCached option.
Fetches fine the first time after app restart and monitoring the network it looks like it downloads the full image only if it is changed, otherwise uses the cache.
But on follow up calls to sd_setImageWithURL within  the same app run it sets an empty image? If I restart the app it sets the correct image the first time, then again empty.
This affects any UIImageView that I try to set the image on with an URL that has already been fetched.

I am severely time pressed, so I can't dive into this right now and will just force reload the image every time I fetch it, but will try to get back to this in a few days.

**Comment by revolter** [comment]
Any news for this PR?

**Comment by bpoplauschi** [comment]
Looks like #2197 has fixed #821 and #1305. Do we still need this PR or we can close it? @dreampiggy @iosnatarajan

**Comment by dreampiggy** [comment]
@bpoplauschi Now we relay on `NSURLSession` to use `NSURLCache` and handle all this 304 not modify response. If this happen, `NSURLSession` will callback you a valid `NSData` from `NSURLCache`. So we can correctly handle that `SDWebImageRefreshCached` options from 4.2.x

So maybe this PR can be closed.

**Comment by dreampiggy** [comment]
Anyway, thanks for your idea about the implementation of this feature. This can be reference by people who don't use `NSURLSession` (Such as build something from the CFNetwork level).

So we just close now. ;)

**Pull request closed without merging**
