### PR TITLE
Using ImageIO UTIs API to check image sources or destinations

### PR DESCRIPTION
**Pull request by zhongwuzw**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have added the required tests to prove the fix/feature I am adding
* [x] I have updated the documentation (if necessary)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / reffers to the following issues: 

### Pull Request Description

Unify the check method of image sources and destinations, using `CGImageSourceCopyTypeIdentifiers` or `CGImageDestinationCopyTypeIdentifiers `.

### CODE REVIEW

**Comment by zhongwuzw** [comment]
@dreampiggy Should I need to close this `PR`? From [WWDC 2017 511](
https://devstreaming-cdn.apple.com/videos/wwdc/2017/511tj33587vdhds/511/511_working_with_heif_and_hevc.pdf), it says:

> One important difference here though between JPEG and HEIF is that creating a CGImageDestination will fail on devices with no HEVC hardware encoder. And when it fails, destination is nil. So, the good defensive code that I wrote on the previous slide, is even more important to do with HEVC where there is now a new reason that the destination might be nil. Please always make sure that you check this is the one and only way to know whether writing to HEIC is supported on your current platform.

**Comment by zhongwuzw** [comment]
`HEIF` and `HEIC`'s writer all use `_kCGImageTypeIdentifierHEIC`, so when I call `CGImageDestinationCopyTypeIdentifiers`, it would not return `public.heif` at all. Am I right?
```
int __Z17CreateWriter_HEIFv() {
    _ImageIO_determine_encodingSupport_HEIF();
    if (*(int8_t *)gHEIF_JPEG_EncodingSupported == 0x1) {
            rbx = operator new(0x28);
            IIO_Writer::IIO_Writer(rbx, _kCGImageTypeIdentifierHEIC, 0x1);
            *rbx = 0x529330;
            *(rbx + 0x20) = @"public.jpeg";
    }
    else {
            rbx = 0x0;
    }
    rax = rbx;
    return rax;
}

int __Z17CreateWriter_HEICv() {
    _ImageIO_determine_encodingSupport_HEIF();
    if (*(int8_t *)gHEIF_HEVC_EncodingSupported == 0x1) {
            rbx = operator new(0x28);
            IIO_Writer::IIO_Writer(rbx, _kCGImageTypeIdentifierHEIC, 0x1);
            *rbx = 0x529330;
            *(rbx + 0x20) = 0x0;
    }
    else {
            rbx = 0x0;
    }
    rax = rbx;
    return rax;
}
```

**Comment by zhongwuzw** [comment]
@dreampiggy 👍 Can you try to test using `CGImageDestinationCreateWithData` and `SDImageFormatHEIF`, as your original code? I test it on `iPhone7+` `iOS11.4`, `destination` not create successful.

**Comment by dreampiggy** [comment]
@zhongwuzw About the `CreateWriter_HEIF`, maybe you are not familiar with HEIF standard. HEIF just like TIFF, it allows you to extend their coding format (codec). The `heic`, actually means the current HEIF image, is encoded with HEVC (H265) codec, which is the modern compression standard of most of video. Which means, HEIF can use some other codec, even like AVCI or JPEG.

Apple also distinguish these two on `CGImageDestination`, which means, when you specify `AVFileTypeHEIF`, you may get a result of heif image which use JPEG codec, for best compatiblity. So I think we should just follow the same thing to avoid the undefined behavior.

**Comment by zhongwuzw** [comment]
@dreampiggy Yeah, thanks for your explanation, I'm not familiar with `HEIF`, I'll watch `WWDC` to get more details. 👍 

And please see my this  [comment](https://github.com/rs/SDWebImage/pull/2425#issuecomment-411042727). 😂

**Comment by dreampiggy** [comment]
@zhongwuzw Currently Apple does not register `public.heif` into Image/IO's IIOWritter. They use `public.heic` only. (However, the Image/IO IIOReader supports both `public.heif` && `public.heic`, really frustrating). So the current system, this `CGImageDestination` will always fail)

But however, as I say, we relay too much of current behavior with hard-code. The better check should as the Apple's demo code, even current iOS 11 does not allow you to speicfy `AVFileTypeHEIF` on `CGImageDestination`, you can not assume that iOS 12 or future Apple introduce this support.

**Comment by dreampiggy** [comment]
@zhongwuzw Since you're Chinese, you can check this [Zhihu site](https://zhuanlan.zhihu.com/p/35847861) about basic HEIF image format. :)

**Comment by zhongwuzw** [comment]
@dreampiggy 👌 , thanks !

**Pull request closed without merging**
