### PR TITLE
Fix animated WebP incorrect render when canvasWidth larger than iter …

### PR DESCRIPTION
**Pull request by CodeLife2012**
### New Pull Request Checklist
- [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
- [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
- [x] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none
- [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
- [ ] I have added the required tests to prove the fix/feature I am adding
- [ ] I have updated the documentation (if necesarry)
- [ ] I have run the tests and they pass
- [ ] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / reffers to the following issues: ...
### Pull Request Description

When use #1438 in our app, we found image is rendered incorrect because first frame's size is not always equal to canvas size.

I just port the [logic in libwebp](https://github.com/webmproject/libwebp/blob/master/examples/vwebp.c#L302).

@lianchengjiang also help check this.

### CODE REVIEW

**Comment by CodeLife2012** [comment]
I run the test in local, `test04CachedImageExistsForURL:` is failed, but seems this fail should not caused by my change.

**Comment by wlegate** [comment]
Any update on this?

**Comment by dreampiggy** [comment]
This is nearly the same fix logic for canvas size issue and disposal method support as #1952

For disposal method support, we should create an CGContext before the iteration start. And then clear the canvas before the frame end if disposal_background.

You implementation use `UIGraphicsBeginImageContextWithOptions` and `UIRectFill` this is `UIKit` specify, we should use `CGBitmapContextCreate` and `CGContextClearRect` for better performance and macOS support. 

Additionaly, there are two more issue in Animated WebP decoding, including duration per frame and Animated WebP loop count. You can check #1951 for more details.

**Comment by bpoplauschi** [comment]
I have merged #1952 , let's close this one and see how it goes.

**Pull request closed without merging**
