### PR TITLE
Import fixes from @harishkashyap 's fork

### PR DESCRIPTION
**Pull request by bpoplauschi**
### Modifies `SDWebImagePrefetcher` prefetching logic
- Removes recursive calls to `startPrefetchingAtIndex`
- Removing separate concurrency from `SDWebImagePrefetcher`, and adding a way to cancel a specific set of operations in the image manager
- This should simplify prefetching and make it easier to prefetch multiple sets of images with the same prefetcher object
- Fixes crashes in `SDWebImagePrefetcher`
  - Fixes crash due to unfinished operation being nil and
  - Fixes crash due to unfinished operation not existing for the requested url key.
- Synchronized access to `prefetchURLs` and `unfinishedOperations` non-thread-safe collections from `SDWebImagePrefetcher`
- Fixed an issue with `self.prefetchURLs` being set to nil on cancel and never recreated to a `NSMutableOrderedSet`

- replaces #999

### CODE REVIEW

**Comment by bpoplauschi** [comment]
@harishkashyap could you take a look and let me know what you think?

**Comment by harishkashyap** [comment]
@bpoplauschi Only the first three commits (ed64e00, ded305f, cbc3433) are mine that improve the existing features and fixes. The later merge request I believe is a drastic change which even removes the earlier feature of prefetching logic and separate concurrency.

**Comment by harishkashyap** [comment]
so you can decide which ones you want to cherry pick.

**Comment by bpoplauschi** [comment]
Got it. I will review this, i thought you reviewed the merge request https://github.com/harishkashyap/SDWebImage/pull/1 and agreed with it, since you merged it into your fork. Agree that changes a few things.

**Comment by bpoplauschi** [comment]
Some more details. It seems https://github.com/rs/SDWebImage/commit/ed64e00d4c0fda4344a3c08acb71eaedde85a5cb was already merged into the master repo via #996. 
https://github.com/rs/SDWebImage/commit/ded305fb28ad55fdc1f39bc3c138ce386f221102 is a merge from master into your branch, so nothing to get from there. 
Final one we should get is: https://github.com/rs/SDWebImage/commit/cbc34337df46840927f9014db113c1b882d7e633

**Comment by harishkashyap** [comment]
That is correct.

**Comment by bpoplauschi** [comment]
Finally integrated this one via merge in commit c8c0081

**Pull request closed without merging**
