### PR TITLE
Update dependency `libwebp` to `~> 0.6.0`. Also, You NEED to update `…

### PR DESCRIPTION
**Pull request by OceanHorn**
Update dependency `libwebp` to `~> 0.6.0`. Also, You NEED to update `libwebp` code reference in this repository.

To solve issue https://github.com/rs/SDWebImage/issues/2167 .

### CODE REVIEW

**Comment by OceanHorn** [comment]
Check fails because the version of `libwebp` in current repository is below `0.5.0`. Update to `0.6.0` is considerable.

**Comment by dreampiggy** [comment]
SDWebImage 4.x submodule's libwebp is already 0.6.0. So this may because of that `iOS-WebP`'s dependency is too low.

It shows `~> 0.5.0`, which means it will match the `0.5.99999`. So this will cause the issue. You should try to ask  `iOS-WebP` to upgrade the dependency.

If you write this in `Podfile`

```ruby
  pod 'SDWebImage/Core', '4.2.3'
  pod 'SDWebImage/WebP', '4.2.3'
  pod 'iOS-WebP', :git => 'git@github.com:seanooi/iOS-WebP.git', :tag => '0.5'
  pod 'libwebp', '0.6.0'
```

image

**Comment by dreampiggy** [comment]
Emmm...But I think, we should also point it out that `SDWebImage/WebP` 's dependency is `libwebp ~> 0.6.0`, I update the dependency but not change code because it already correct.

**Comment by dreampiggy** [comment]
Merged by #2169

**Pull request closed without merging**
