### PR TITLE
Provide a way to fix libwebp’s bug during WebP progressive decoding f…

### PR DESCRIPTION
**Pull request by dreampiggy**
…or x86 architecture (macOS and iPhone simulator). It kept the previous decoded partial bitmap and will cause current image looks strange.

### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have added the required tests to prove the fix/feature I am adding
* [x] I have updated the documentation (if necessary)
* [x] I have run the tests and they pass // wait for master branch to pass the test
* [x] I have run the lint and it passes (`pod lib lint`) // it compiled failed on macOS. Don't worry, I'll open another PR to fix

This merge request fixes / reffers to the following issues: 

### Pull Request Description

The all what I want to say is under that commit message and code comments :)

```objective-c
// Why to use last_y for image height is because of libwebp's bug (https://bugs.chromium.org/p/webp/issues/detail?id=362)
// It will not keep memory barrier safe on x86 architechure (macOS & iPhone simulator) but on ARM architecture (iPhone & iPad & tv & watch) it works great
// If different threads use WebPIDecGetRGB to grab rgba bitmap, it will contain the previous decoded bitmap data
// So this will cause our drawed image looks strange(above is the current part but below is the previous part)
// We only grab the last_y height and draw the last_y heigh instead of total height image
// Besides fix, this can enhance performance since we do not need to create extra bitmap
// Only draw the last_y image height, keep remains transparent, in Core Graphics coordinate system
```

### CODE REVIEW

**Comment by bpoplauschi** [comment]
Looks good - waiting for the build

**Comment by dreampiggy** [comment]
@bpoplauschi Sorry that GIF encoding method compile failed on macOS. I'm fixing it. Another PR is prepared. 😢

**Comment by bpoplauschi** [comment]
@dreampiggy I already fixed it on master :)

**Comment by dreampiggy** [comment]
@bpoplauschi This bug was found during that original progressive webp encoding's PR. I test with iPhone device it works fine. So I think this may be a iPhone simulator bug. But accidentally I try progressive webp decoding on macOS. It also trigger this bug. So I finally find a tricky way to fix it(looks good) and submit a bug report to WebP community. 😫

**Comment by bpoplauschi** [comment]
Great work @dreampiggy so you are sharing the fix with the WebP community and until that is available in a release from them, we have a working workaround. Excellent.

**Comment by bpoplauschi** [comment]
Master build works now :) I just disabled that test. Let's merge this in

**Pull request merged**
