### PR TITLE
Memory Leak bug fixed.

### PR DESCRIPTION
**Pull request by RbBtSn0w**
destBitmapData was beyond the scope.

### CODE REVIEW

**Comment by worldofnick** [comment]
+1

**Comment by bpoplauschi** [comment]
@RbBtSn0w I'm not sure about this. Look at `CGBitmapContextCreate`. Doc says:

> Creates a bitmap graphics context.
When you draw into this context, Core Graphics renders your drawing as bitmapped data in the specified block of memory.

So basically we need `destBitmapData` later on when we draw with `CGContextDrawImage`.

We might try to release it after that.

**Comment by dreampiggy** [comment]
Interestring, `CGBitmapContextCreate` use the first param to provide the output bitmap vector if you want low-level bitmap operation(such as low-level blur effect, transform, encoding). But here I find that `destBitmapData` is not been used on later procedure. So maybe it's useless and this will cause memory leak here because you only call `CGContextRelease(destContext)` to free CGContext but forget to call `free(destBitmapData)` to free bitmap before the total function return.

If you do not need low-level bitmap operation, just do what Apple Doc says: `Pass NULL if you want this function to allocate memory for the bitmap. This frees you from managing your own memory, which reduces memory leak issues.` 

The code may look like this:

```objectivec
destContext = CGBitmapContextCreate(NULL,
                                    destResolution.width,
                                    destResolution.height,
                                    kBitsPerComponent,
                                    bytesPerRow,
                                    colorspaceRef,
                                    kCGBitmapByteOrderDefault|kCGImageAlphaNoneSkipLast);

if (!destContext) {
    return image;
}
```

**Comment by dreampiggy** [comment]
I try the Demo (tweak the `DetailViewController.m` and use this test code), when using Instruments, it show that there is exact memory leak.

```objectivec
- (void)configureView
{
    if (self.imageURL) {
        NSString * testImagePath = @"/tmp/TestImageLarge.jpg"; // I put that image from Test project to my temp folder
        UIImage *image = [UIImage imageWithContentsOfFile:testImagePath];
        UIImage *decodedImage = [UIImage decodedAndScaledDownImageWithImage:image];
        self.imageView.image = decodedImage;
    }
}
```

**Comment by bpoplauschi** [comment]
Should be fixed by #1976

**Pull request closed without merging**
