### PR TITLE
Add support for downloading images behind redirect

### PR DESCRIPTION
**Pull request by mackoj**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have added the required tests to prove the fix/feature I am adding
* [x] I have updated the documentation (if necesarry)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

### Pull Request Description

This merge request add the support for downloading images that are behind an HTTP redirect.

### CODE REVIEW

**Comment by mackoj** [comment]
It's work locally but not on travis.

**Comment by andyden9** [comment]
The image successfully downloaded (Charles shows that the image is downloaded and image SHOWN in my own demo) but this very test STILL fails and reports error.

Might be the problem with this test itself, or maybe some internal instance naming issue
```
expect(originalImageURL).toNot.equal(imageURL);
```

I think 'originalImageURL' is always the same with 'imageURL'(`sd_imageURL` also won't work), maybe imageURL didn't change the whole time.

I post the error message below, hope it helps with your test.

Test Suite 'Selected tests' started at 2016-09-01 12:08:37.613
Test Suite 'SDWebImageManagerTests' started at 2016-09-01 12:08:37.614
Test Case '-[SDWebImageManagerTests testTestThatItCanDownloadAnImageWithARedirection]' started.
-waitForExpectationsWithTimeout: timed out but was unable to run the timeout handler because the main thread was unresponsive (0.5 seconds is allowed after the wait times out). Conditions that may cause this include processing blocking IO on the main thread, calls to sleep(), deadlocks, and synchronous IPC.

```Objective-C
2016-09-01 12:10:39.673 xctest[76226:9073983]/Users/andyden9/Desktop/SDWebImage/SDWebImage/Tests/Tests/SDWebImageManagerTests.m:81: error: -[SDWebImageManagerTests testTestThatItCanDownloadAnImageWithARedirection] : expected: not http://cx500forum.com/forum/attachment.php?attachmentid=14656&d=1408526626, got: http://cx500forum.com/forum/attachment.php?attachmentid=14656&d=1408526626
```

**Comment by mackoj** [comment]
I think it's just an issue with Travis.

@bpoplauschi could you take a look at this please ? The code is working the test is working locally but not on Travis.

**Comment by mackoj** [comment]
I will remove the test

**Comment by luohui8891** [comment]
This PR also fix my [case](https://github.com/rs/SDWebImage/issues/1639#issuecomment-235846158)
Thanks dude.

**Comment by mythodeia** [comment]
@bpoplauschi ready to merge this?

**Comment by bpoplauschi** [comment]
Looks good. But we should try to make the test work as well. Better coverage that way.

**Comment by mackoj** [comment]
I think the best way to do a good test is to host an image behind a redirection... 
Because I try with facebook it's work locally but not on travis because I think facebook may have block them ?

**Comment by bpoplauschi** [comment]
Ok, I merged it into the 4.x branch, for now thats it. Thanks

**Comment by luohui8891** [comment]
@mackoj hey, I saw 4.0.0 has been released. 
I tried my [case](http://cx500forum.com/forum/attachment.php?attachmentid=14656&d=1408526626) again both in 4.0.0 and master. 
No luck, it didn't work.

**How to reproduce:**

- Open the demo project `SDWebImage Demo`.
- Open the file `MasterViewController.m`
- Add this link `@"http://cx500forum.com/forum/attachment.php?attachmentid=14656&d=1408526626"` in the array `_objects` (line 68)
- Run the demo.

The delegate method `- (void)URLSession:(NSURLSession *)session dataTask:(NSURLSessionDataTask *)dataTask willCacheResponse:(NSCachedURLResponse *)proposedResponse completionHandler:(void (^)(NSCachedURLResponse *cachedResponse))completionHandler` didn't been called.
 Do you have any idea?

**Comment by mackoj** [comment]
Hi @luohui8891,

It's does not seems to work for me either even with curl.

```
➜  curl http://cx500forum.com/forum/attachment.php\?attachmentid\=14656\&d\=1408526626 -v -o 028.JPG   
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 50.97.177.71...
* TCP_NODELAY set
* Connected to cx500forum.com (50.97.177.71) port 80 (#0)
> GET /forum/attachment.php?attachmentid=14656&d=1408526626 HTTP/1.1
> Host: cx500forum.com
> User-Agent: curl/7.51.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Date: Fri, 17 Feb 2017 08:43:12 GMT
< Server: Apache
< X-Powered-By: PHP/5.4.45-0+deb7u6
< Vary: User-Agent
< Pragma: 
< Cache-control: max-age=31536000, private
< Expires: Sat, 17 Feb 2018 08:43:12 GMT
< Last-Modified: Wed, 20 Aug 2014 09:23:46 GMT
< ETag: "14656"
< Accept-Ranges: bytes
< Content-disposition: inline; filename="028.JPG"
< Content-transfer-encoding: binary
< X-Content-Type-Options: nosniff
< X-Permitted-Cross-Domain-Policies: none
< Content-Length: 1754588
< Location: http://cx500forum.com/forum/attachments/general-discussion/14656-ciao-tutti-dallitalia-028.jpg
< Content-Type: image/jpeg
< 
  0 1713k    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0{ [0 bytes data]
* transfer closed with 1754588 bytes remaining to read
* Curl_http_done: called premature == 1
  0 1713k    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
* Closing connection 0
curl: (18) transfer closed with 1754588 bytes remaining to read
```

**Comment by luohui8891** [comment]
@mackoj right. Thanks for quick reply.
But it works when I parsed it in Chrome and Safari on my iPhone.

Saw the previous comment
>This PR also fix my case
Thanks dude.

I also checkout code to the [commit](https://github.com/rs/SDWebImage/pull/1657/commits/9d0e0c11185e0afe63f9bfcd72aa2fcdcc63ffb6) of this pull commit, the URL didn't work yet. But I forgot why I said that.

I didn't understand the delegate method very clear. Do you know when it would be called? Any example?

**Comment by xiaowu1225** [comment]
I have solve this problem by add the following code:
[[SDWebImageManager sharedManager].imageDownloader setValue:@"*/*" forHTTPHeaderField:@"Accept"];
Hope to be able to help people who meet this problem！

**Comment by bpoplauschi** [comment]
@mackoj Thanks a lot for showing interest and contributing to SDWebImage! 
We would like to invite you to become a maintainer – no pressure to accept! At this point we are only a handful of people doing this in our spare time. 
I am working on writing down the expectations from contributors, but basically

> we want contributors to provide ideas, keep the ship shipping and to take some of the load from others. It is non-obligatory; we’re here to get things done in an enjoyable way. 

Pitch in with what seems comfortable: comment on open issues/PRs, triage, improve documentation, write your own PRs.
Let us know.

Quote from [Moya Contributing guide](https://github.com/Moya/Moya/blob/master/Contributing.md#our-expectations-on-you-as-a-contributor).

**Comment by bpoplauschi** [comment]
Ping @mackoj

**Pull request merged**
