### PR TITLE
Added method to add new urls to the SDWebImagePrefetcher array of prefetchURLs

### PR DESCRIPTION
**Pull request by zigadolar**
If the prefetcher is already prefetching URLs, this method adds an array of URLs to the existing prefetchURLs, otherwise it calls prefetchURLs:

### CODE REVIEW

**Comment by bpoplauschi** [comment]
Not sure if this method would be safe. It alters a mutable container that might be enumerated.

**Comment by mythodeia** [comment]
i agree with @bpoplauschi here. we do not know if the prefetch array is being enumerated while we add more urls to it.

**Comment by bpoplauschi** [comment]
@zigadolar can you respond to our comments?

**Comment by zigadolar** [comment]
@bpoplauschi I am sorry for the late replies. The prefetchURLs is not mutable, that's why in adding additional urls it is replaced in it's entirety with a new array, with the new urls appended to the end of the previous one.

@mythodeia I don't see where it would be enumerated, as all methods only check the prefetchURLs count or request an url by index from the array, where I suppose an issue would be, if we were removing urls from the array, and would be risking and index out of bounds crash. Where do you suspect this crash would happen - and any idea how to test for it?

**Comment by mythodeia** [comment]
@zigadolar there is an enumeration but you are right as its not removing any elements there. 
its only calling the ```startPrefetchingAtIndex``` method.
My concern is like you said, if by any chance you try to get a specific element of the array from within the ```startPrefetchingAtIndex``` method,  when in fact that index is out of bounds (if the prefetchUrl array has changed by the user)

**Comment by zigadolar** [comment]
@mythodeia at the start of the `startPrefetchingAtIndex:` method there is a check for array bounds, that returns, if the index is in fact out of bounds. But the user can not actually interfere with the prefetchURLs array directly anyway - that is the purpose of the `addPrefetchURLs:` method: to only be able to add more URLs to the existing array (or creating a new one from the previously already existing method `prefetchURLs:`, if it doesn't exist yet), so there would always only be more items in the array and never fewer.

**Comment by mythodeia** [comment]
@zigadolar makes sense. @bpoplauschi are you ok with this?

**Comment by bpoplauschi** [comment]
> so there would always only be more items in the array and never fewer.
I don't agree. Even if we guarantee that the number of items is larger, there is still an issue of data synchronisation. The idea would be that while enumerating or interacting with a collection, nobody should change the contents of that collection. `startPrefetchingAtIndex:` could be executed at the same time as `addPrefetchURLs:`. Because `startPrefetchingAtIndex:` works with indexes of the array, we will at least have a logical issue (if not a crash).  We need to synchronise access to the `prefetchURLs` and we need this for the existing code (even without this patch here).

**Comment by bpoplauschi** [comment]
Closing, based on the conversation.

**Pull request closed without merging**
