### PR TITLE
Fix crash when assign request property of SDWebImageDownloadToken

### LINKED ISSUE #2380: Crash when assign request property of SDWebImageDownloadToken
* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 11.4 Simulator
 SDWebImage Version      | [branch 5.x](https://github.com/rs/SDWebImage/tree/5.x)
 Integration Method      | manually
 Xcode Version           | Xcode 9 
 Repro rate              | only once
 Repro with our demo prj | yes
 Demo project link       | just prj demo

Crash bt:

```
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x20)
  * frame #0: 0x0000000117d390e5 CFNetwork`HTTPParser::HTTPParser(__CFAllocator const*, HTTPParserClient*, HTTPParser*) + 45
    frame #1: 0x0000000117d37d6c CFNetwork`HTTPMessage::commonInitialization(unsigned char, HTTPMessage const*) + 320
    frame #2: 0x0000000117d38f4e CFNetwork`HTTPRequestMessage::HTTPRequestMessage(HTTPRequestMessage const*) + 28
    frame #3: 0x0000000117d38eec CFNetwork`HTTPRequest::HTTPRequest(HTTPRequest const*) + 18
    frame #4: 0x0000000117d35bc1 CFNetwork`URLRequest::initialize(URLRequest const*, unsigned char) + 661
    frame #5: 0x0000000117d35902 CFNetwork`_createRequestCopy(__CFAllocator const*, _CFURLRequest const*, unsigned char) + 187
    frame #6: 0x0000000117d38e92 CFNetwork`-[NSURLRequest mutableCopyWithZone:] + 36
    frame #7: 0x0000000110dff4a2 libobjc.A.dylib`objc_setProperty_nonatomic_copy + 39
    frame #8: 0x00000001105a0e47 SDWebImage`-[SDWebImageDownloadToken setRequest:](self=0x0000604000466300, _cmd="setRequest:", request=0x0000604000013bf0) at SDWebImageDownloader.m:22
    frame #9: 0x000000011059f11f SDWebImage`-[SDWebImageDownloader addProgressCallback:completedBlock:forURL:createCallback:](self=0x000060000009f8b0, _cmd="addProgressCallback:completedBlock:forURL:createCallback:", progressBlock=0x00000001105f2e80, completedBlock=0x00000001105a4c00, url=@"https://s3.amazonaws.com/fast-image-cache/demo-images/FICDDemoImage001.jpg", createCallback=0x000000011059dc00) at SDWebImageDownloader.m:289
    frame #10: 0x000000011059daf0 SDWebImage`-[SDWebImageDownloader downloadImageWithURL:options:context:progress:completed:](self=0x000060000009f8b0, _cmd="downloadImageWithURL:options:context:progress:completed:", url=@"https://s3.amazonaws.com/fast-image-cache/demo-images/FICDDemoImage001.jpg", options=0, context=0x0000604000222920, progressBlock=0x00000001105f2e80, completedBlock=0x00000001105a4c00) at SDWebImageDownloader.m:163
    frame #11: 0x00000001105a1416 SDWebImage`-[SDWebImageDownloader(self=0x000060000009f8b0, _cmd="loadImageWithURL:options:context:progress:completed:", url=@"https://s3.amazonaws.com/fast-image-cache/demo-images/FICDDemoImage001.jpg", options=0, context=0x0000604000222920, progressBlock=0x00000001105f2e80, completedBlock=0x00000001105a4c00) loadImageWithURL:options:context:progress:completed:] at SDWebImageDownloader.m:499
    frame #12: 0x00000001105a4900 SDWebImage`-[SDWebImageManager callDownloadProcessForOperation:url:options:context:cachedImage:cachedData:cacheType:progress:completed:](self=0x00006000000b7700, _cmd="callDownloadProcessForOperation:url:options:context:cachedImage:cachedData:cacheType:progress:completed:", operation=0x000060400024bf40, url=@"https://s3.amazonaws.com/fast-image-cache/demo-images/FICDDemoImage001.jpg", options=0, context=0x0000604000222920, cachedImage=0x0000000000000000, cachedData=0x0000000000000000, cacheType=SDImageCacheTypeDisk, progressBlock=0x00000001105f2e80, completedBlock=0x00000001105f3270) at SDWebImageManager.m:245
    frame #13: 0x00000001105a4087 SDWebImage`__89-[SDWebImageManager callCacheProcessForOperation:url:options:context:progress:completed:]_block_invoke(.block_descriptor=0x00006040002a0780, cachedImage=0x0000000000000000, cachedData=0x0000000000000000, cacheType=SDImageCacheTypeDisk) at SDWebImageManager.m:205
    frame #14: 0x00000001105ebdd4 SDWebImage`__63-[SDImageCache queryCacheOperationForKey:options:context:done:]_block_invoke_2(.block_descriptor=0x0000600000676500) at SDImageCache.m:398
    frame #15: 0x000000011648c7ab libdispatch.dylib`_dispatch_call_block_and_release + 12
    frame #16: 0x000000011648d7ec libdispatch.dylib`_dispatch_client_callout + 8
    frame #17: 0x00000001164988cf libdispatch.dylib`_dispatch_main_queue_callback_4CF + 628
    frame #18: 0x000000011171ec99 CoreFoundation`__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
    frame #19: 0x00000001116e2ea6 CoreFoundation`__CFRunLoopRun + 2342
    frame #20: 0x00000001116e230b CoreFoundation`CFRunLoopRunSpecific + 635
    frame #21: 0x00000001140f2a73 GraphicsServices`GSEventRunModal + 62
    frame #22: 0x000000010dd44057 UIKit`UIApplicationMain + 159
    frame #23: 0x000000010cf65f6f SDWebImage iOS Demo`main(argc=1, argv=0x00007ffee2c98eb0) at main.m:16
    frame #24: 0x000000011650a955 libdyld.dylib`start + 1
```

### PR DESCRIPTION
**Pull request by zhongwuzw**
* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [ ] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [ ] I have added the required tests to prove the fix/feature I am adding
* [ ] I have updated the documentation (if necessary)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

Fixed #2380 .

### CODE REVIEW

**Comment by zhongwuzw** [comment]
Reason I change the attribute to `strong` is:
Actually, we don't need to copy at all. The `request` and `response` are `readonly` to public.
Even they can be modify, they still have not any effect to `NSURLSession`.

**Comment by dreampiggy** [comment]
@zhongwuzw 😅 I saw you contribue some PRs for SDWebImage, and your skill about the framework development, Objective-C/C seems good enough. We're all some people who spend spare time to contribute to Open Source project, but we seems lack of new people to develop it further.

If you're intereted in it and have the hope, I can ask bpoplauschi to introduce you to the SDWebImage's Collaborator and contribute to the project easier. You can review others changes, write documentations, check and fire issue tags, push to branches, etc.

This does not means that there are some "daily tasks, works or missions force you to do". We just think if you're interested in this project and want to contribute more, this can make it easier.

**Comment by zhongwuzw** [comment]
@dreampiggy Thanks for your invitations. 👍 I'd be glad and honor to be the `Collaborator` of `SDWebImage`. I'm the open source enthusiast, and more, I love `SDWebImage` and almost use it in all the apps I participate. I would look in depth to the whole framework, learn and the same time, propose some fixes, optimizations or something .

Thanks again! 🍻

**Comment by bpoplauschi** [comment]
I agree with @dreampiggy's proposal here. @zhongwuzw you have proved your worth here.
@rs can we add @zhongwuzw as a collaborator?

**Comment by rs** [comment]
Invitation sent.

**Comment by bpoplauschi** [comment]
Appreciate it, @rs

**Comment by zhongwuzw** [comment]
@bpoplauschi Yeah, thanks and appreciate! 🍻🍻🍻

**Comment by dreampiggy** [comment]
@zhongwuzw Welcome ;)

**Pull request merged**
