### PR TITLE
Fixing casing for #import "webp/decode.h"

### PR DESCRIPTION
**Pull request by unlucio**
webp needs to be WebP of compile will not work on case sensitive HDs

### CODE REVIEW

**Comment by mythodeia** [comment]
why is it WebP? i see that the webp folder is lowercased in both disk and xcode group.
are you talking about something else?

**Comment by unlucio** [comment]
@mythodeia ouch yes: I found the compile problem on a private project but I guess the webp filer name changes mean while.
My bad.

**Comment by mythodeia** [comment]
@bpoplauschi can you revert pls?

**Comment by bpoplauschi** [comment]
Done in b111d62

**Pull request merged**
