### PR TITLE
Add targets for core frameworks without MapKit, WebP and FLAnimatedImage

### PR DESCRIPTION
**Pull request by BlueVirusX**
### New Pull Request Checklist

* [X] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [X] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [X] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [X] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [X] I have added the required tests to prove the fix/feature I am adding
* [X] I have updated the documentation (if necessary)
* [X] I have run the tests and they pass
* [X] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / reffers to the following issues: #2056

### Pull Request Description
Add targets for core frameworks without MapKit, WebP and FLAnimatedImage.
The new targets allow developers to use the [core parts](https://github.com/rs/SDWebImage/blob/master/SDWebImage.podspec#L29) of SDWebImage in combination with Carthage without the need to include MapKit.

### CODE REVIEW

**Comment by dreampiggy** [comment]
Any idea about this ? For carthage, do we have some ways to config build target like Cocoapods' subspec. Must we create seperate scheme for different subspec ?

In fact, this will be more problems: What can I do if I just want `Core && WebP` subspec using carthage. Considerate all the subspec, there will be`3(subspec count)! == 6` combination. Which is really tricky.

**Comment by bpoplauschi** [comment]
@dreampiggy I don't think Carthage supports "subspecs" And indeed there is a problem with not being able to support all combinations.
I haven't merged this PR already because:
- on one hand, I understand the problem @BlueVirusX is facing and it can be solved if we keep a set of xcodeproj targets with core only
- on the other hand, we already have quite a few targets there and creating more will just complicate things. Even now is a bit difficult when adding a file to the project to make sure is included in all proper targets (not necessarily all targets). At this point, the dimension of the targets is the platform (and sometimes static vs dynamic). So we have a static iOS lib and a dynamic iOS framework, but also a dynamic watchOS framework. Adding another level of depth with core/map/gif/... components will just make maintenance impossible.

**Comment by bpoplauschi** [comment]
See https://github.com/Carthage/Carthage/issues/588
I think their message is: split large frameworks into smaller ones. So we could do this, I guess.
Something like:
SDWebImageCore.framework, then SDWebImageMap.framework that links to the first.

**Comment by dreampiggy** [comment]
It seems that SDWebImage 5.x does not really need `FLAnimatedImage` for animated image rendering. And I've remove the tricky code specify for FL, see #2162. Then can we seperate `FLAnimatedImage` into a different cocoapods ? I think this can make the library more easy to maintain and avoid carthage import the FLAnimatedImage as well.

For WebP, this seems you can do this by undefine the `SD_WEBP` by override `GCC_PREPROCESSOR_DEFINITIONS` using Carthage's `XCODE_XCCONFIG_FILE`

**Comment by priteshshah1983** [comment]
Since both Cocoapods and Carthage support dependencies, can `FLAnimatedImage` be declared as a dependency in the `podspec` and `Cartfile` respectively instead of bundling it? Is it specifically bundled in `Vendors` to support the manual installation use-case?

Please let me know if I'm missing something. In my case, I'm trying to use `SDWebImage` in a Carthage project that already uses `FLAnimatedImage` and running into `Duplicate interface definition for class 'FLAnimatedImageView'`. If Carthage supported subspecs, I could have only imported `SDWebImage/Core` instead, but it doesn't.

**Comment by bpoplauschi** [comment]
@priteshshah1983 I understand your issue. Let me give some context and then we can think about what to do next, except doing nothing :)
- a long time ago, `libwebp` was the only dependency of this project and got added via git submodules (at that time, it didn't have CocoaPods or Carthage support. In the meantime, we managed to add it to CocoaPods).
- when making the 4.x rewrite, we added `FLAnimatedImage` as a dependency to deal with the animated images - it was performing way better than our code (based on the Apple high level APIs). So we added it using the same pattern aka git submodules.
- now here we are
- indeed, for the future, we can do something about this.
- @dreampiggy's idea sounds good (moving the FLAnimatedImage code to a separate project). Wonder if we can do the same for the other subspecs. We need to look deep into this. But I immediately spot a potential issue with libwebp that doesn't support Carthage (doesn't have an xcodeproj). So if the libwebp files are not in our repo (as they are now by git submodules), we won't be able to support Carthage for libwebp. To be explored...
- CC @mythodeia @skyline75489 @rs what do you guys think?

**Comment by bpoplauschi** [comment]
An update here: I think we are going to remove `FLAnimatedImage` entirely from the 5.x version - see #2140

**Comment by bpoplauschi** [comment]
We did remove `FLAnimatedImage` on the 5.x branch, so that makes things a bit easier. We still don't have a way to import SDWebImage via Carthage without MapKit.

**Comment by bpoplauschi** [comment]
Currently, since we have removed `FLAnimatedImage` from `5.x`, we still have issues with:
- `webp` dependency
- `MapKit` dependency.

I still don't think keeping a lot of targets around (we already have too many) is a good option.
So looking past that:
- we could move `SDImageWebPCoder` to a dedicated repo that lists `libwep` as a dependency. That project would still need to link to `libwebp` as a git submodule since we can't use Carthage - missing xcodeproj in their repo. But at least people who explicitly add that to their Cartfile will do so explicitly
- if we want the same result with MapKit, we could also create a project for the MapKit plugin, but that would only contain `MKAnnotationView+WebCache` so I don't know, sounds like over-engineering to me

**Comment by bpoplauschi** [comment]
Actually, looking at https://github.com/pinterest/PINRemoteImage/blob/master/Cartfile I can see we can reference libwebp via Carthage, even though they do not have an xcodeproj:
`git "https://chromium.googlesource.com/webm/libwebp" "v0.6.0"`

**Comment by bpoplauschi** [comment]
@dreampiggy @zhongwuzw what do you think? Is it a good idea to move all the WebP stuff (code, issues, ...) into a dedicated project like `SDWebPCoder`? Will match our pattern and will make it easier for us.

**Comment by dreampiggy** [comment]
Does a Cartfile with that `git "https://chromium.googlesource.com/webm/libwebp" "v0.6.0"` successfully work ? Carthage build will automatically download the git repo of libwebp and build ? But there are no any xcproject

**Comment by dreampiggy** [comment]
From current coder architecture, it's possible because each image format decoder are separated like a plugin. We can just move all WebP code into a dedicated repo.

MapKit support is quite simple, I guess the most of reason they move MapKit into another dedicated repo, it's because of App Store review. See ReactiveCocoa and the reason they create ReactiveMapKit. 
https://github.com/ReactiveCocoa/ReactiveCocoa/pull/3524

I'm typing on mobile and going to sleep now...The reply may take longer...😅

**Comment by bpoplauschi** [comment]
Appreciate your night quick response @dreampiggy :)

**Comment by bpoplauschi** [comment]
> Does a Cartfile with that git "https://chromium.googlesource.com/webm/libwebp" "v0.6.0" successfully work ? Carthage build will automatically download the git repo of libwebp and build ? But there are no any xcproject

I thought the same, but it seems these guys from Pinterest are using libwebp via Carthage. Need to investigate

**Comment by bpoplauschi** [comment]
> MapKit support is quite simple, I guess the most of reason some user want to build without MapKit, it's because of App Store review (I'm doubt of that). See ReactiveCocoa and the reason they create ReactiveMapKit.
ReactiveCocoa/ReactiveCocoa#3524
ReactiveCocoa/ReactiveCocoa#3521

Basically, they did the same as the proposal from @BlueVirusX, just keep another target with MapKit. I would explore other options before going to that.

**Comment by bpoplauschi** [comment]
One thing I noticed recently is we could have a single target in Xcode that is built for multiple platforms, so I think we can merge all `SDWebImage iOS` + `SDWebImage tvOS` + `SDWebImage watchOS` + `SDWebImage OSX` = `SDWebImage` with all 4 platforms.
Same for `SDWebImage iOS static` + `SDWebImage watchOS static` = `SDWebImage static` supporting `ios` and `watchos`.

**Comment by bpoplauschi** [comment]
Another idea is to use a proxy like https://github.com/zetasq/CWebP which basically contains an xcodeproj with shared targets and links to the libwebp project as git submodule

**Comment by bpoplauschi** [comment]
Per this conversation, I have created:
- [SDWebImage/libwebp-Xcode](https://github.com/SDWebImage/libwebp-Xcode) which is very similar to CWebP, but cleaner (we don't keep any copies of the source files). This basically links to libwebp as a git submodule and adds an Xcode project to it.
- [SDWebImage/SDImageWebPCoder](https://github.com/SDWebImage/SDImageWebPCoder) containing all the `WebP` integration. This is very similar to [SDWebImage/SDWebImageFLPlugin](https://github.com/SDWebImage/SDWebImageFLPlugin)

If everything is ok, on the 5.x branch we will remove the `WebP` related files and subspec.

**Comment by bpoplauschi** [comment]
I think this PR will be closed once we merge #2469 and e7e3466

**Comment by bpoplauschi** [comment]
#2469 was merged to 5.x branch. #2476 is up for review. I will go ahead and close this one.
@BlueVirusX thanks for making the initial PR, it took us a while but I think we have come up with a good solution.

**Pull request closed without merging**
