### PR TITLE
Fix function storeImageDataToDisk description

### PR DESCRIPTION
**Pull request by plokijuhhb**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have added the required tests to prove the fix/feature I am adding
* [x] I have updated the documentation (if necessary)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / reffers to the following issues: ...

#### Description
`-[SDImageCache storeImageDataToDisk:forKey:]` when call it from the `ioQueue`, will deadlock
There are some problems in this description

Or using marco like SDWebImageCompat avoid deadlocks
```
#ifndef dispatch_queue_sync_safe
#define dispatch_queue_sync_safe(queue, block)\
if (strcmp(dispatch_queue_get_label(DISPATCH_CURRENT_QUEUE_LABEL), dispatch_queue_get_label(queue)) == 0) {\
block();\
} else {\
dispatch_sync(queue, block);\
}
#endif
```

### CODE REVIEW

**Comment by dreampiggy** [comment]
How can you get access from `ioQueue` ?

**Comment by plokijuhhb** [comment]
😀

**Comment by bpoplauschi** [comment]
@dreampiggy this is from the latest master (unreleased 4.3.4):
```objective-c
- (void)storeImageDataToDisk:(nullable NSData *)imageData forKey:(nullable NSString *)key {
    if (!imageData || !key) {
        return;
    }
    dispatch_sync(self.ioQueue, ^{
        [self _storeImageDataToDisk:imageData forKey:key];
    });
}
```
so the comment makes perfect sense. If you call this method from the ioQueue, it will deadlock because of the `dispatch_sync`.

**Comment by bpoplauschi** [comment]
@dreampiggy the refactoring you mentioned was in 5.x, so this PR applies for 4.3.4. I will merge it.

**Comment by dreampiggy** [comment]
@bpoplauschi The fact is...You can not get `ioQueue` because it's private property inside. Well, we should know this in the implementation, but don't need to describe this on the public method documentations. Which cause user confused because there are no such a `ioQueue` property. 😀

**Comment by dreampiggy** [comment]
@bpoplauschi I'd like to just remove that line of `@warning`, which is better. (The above already tell that this method is Synchronous)...

**Comment by bpoplauschi** [comment]
22e532c

**Pull request merged**
