### PR TITLE
Fixed retain cycle in SDWebImageManager

### PR DESCRIPTION
**Pull request by martinpilch**
Just fixing a retain cycle in `SDWebImageManager` inside `cancelBlock`.

### CODE REVIEW

**Comment by bpoplauschi** [comment]
@martinpilch Please take a look at all the code regarding the sync on `self.runningOperations`. If there is an issue, it's in multiple places.

**Comment by martinpilch** [comment]
@bpoplauschi Will do it and let you know

**Comment by bpoplauschi** [comment]
Thanks. I plan to look at this too, but I have other more urgent tickets

**Comment by bpoplauschi** [comment]
Any updates here? @martinpilch can you share some Instruments trace that show this retain cycle?

**Comment by bpoplauschi** [comment]
Since the code changed on the 4.x, branch I have replaced this PR with 9cd6779. No need to weakify self since it's usually a singleton.

**Pull request closed without merging**
