### PR TITLE
Feature image transformer

### PR DESCRIPTION
**Pull request by dreampiggy**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have added the required tests to prove the fix/feature I am adding // Done. Add 8 tests, also available for macOS :)
* [x] I have updated the documentation (if necessary)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / reffers to the following issues: #1270

### Reason

Image Transforming is a feature to transform the image download from network or disk cache, to another format. You can do resizing, scaling, cropping, rotatation, flipping or advanced process like blur effect or CIFilter.

For example, if you want to clip a round corner image after the original image download. For Kingfisher, you can use [Transform downloaded image to round corner before displaying and caching
](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#transform-downloaded-image-to-round-corner-before-displaying-and-caching).

Through we have a completionBlock after image load. However, you can not easily store this to disk cache and retrieve again when you next time call `sd_setImageWithURL:`. Through if you really want to do so, you need really complicated code and it's hard to maintain. (First, you need the delegate methods `[-
imageManager:transformDownloadedImage:withURL:]` and do a huge switch case to the URL to decide which request need which transform. Next, you need to grab the URL again from your own manager. Actually I saw my company's people bind each `SDWebImageManager` to their transformer manager to achive this feature. It's really trick.)

And to say, our company's application need some transform such like resizing or rounded corner for better performance and experience. I think we can do this by refactoring the current transform way and allow user to easily use this. And more importantly, it's one reason why some people prefer to choose Kingfisher :)

### Design
From the description above, we need a protocol to allow user to provide their implementation because user desired image transforming is widely different. For this protocol, first we must contains a method to transform the original image to another image. So I create `-[SDWebImageTransformer transformedImageWithImage:forKey:]`

And then,  we know that this transformer should be used to store into cache and for further retrieve. But we should not override the original image in disk cache, and one transformed image must contains their own key to allow furture retrieve. So we also need a method to get the cache key. We append the cacheKey after the original cache key and avoid conflict. So I create `-[SDWebImageTransformer transformerKey]`.

> original key: `http://image.png`
> resize key:
>`http://image-SDWebImageResizingTransformer(100,100).png`

And the most exciting way is that to chain the transformer, for example, if we want to firstly rounded corner the image(`20 radius, all corners, 0 border and clear color`), then do a rotation(`pi/4 angle, fitSize`), we can create a `SDWebImagePipelineTransformer` combine these two transformer. And the cache key could be also combined to avoid conflict.

> rounded corner |> rotation key:
>`http://image-SDWebImageRoundCornerTransformer(20,15,0,#00000000)-SDWebImageRotationTransformer(0.78539816339,1).png`

### Implementation
The protocol may looks like this:

```objective-c
@protocol SDWebImageTransformer <NSObject>

@required
/**
 For each transformer, it must contains its cache key to used to store the image cache or query from the cache. This key will be appened after the original cache key generated by URL or from user.

 @return The cache key to appended after the original cache key. Should not be nil.
 */
- (nonnull NSString *)transformerKey;

/**
 Transform the image to another image.

 @param image The image to be transformed
 @param key The cache key associated to the image
 @return The transformed image, or nil if transform failed
 */
- (nullable UIImage *)transformedImageWithImage:(nonnull UIImage *)image forKey:(nonnull NSString *)key;

@end
```

And for image processing code, such as image resizing, image blur effect. I reference the code from [YYCategories](https://github.com/ibireme/YYCategories)(MIT Licence). Then reimplement it to make it work for UIKit/AppKit. Some image processing code are written by myself and I've test that works.

### CODE REVIEW

**Comment by dreampiggy** [comment]
This is also a big feature because we need many image process code. Through I reference some from others and this should work. There may be some race condition or bugs. I just firstlly publish this PR to make furture development.

Anyone contains idea about image transfomer can also comment here. Such as your use case about transforming. So we can have a clear aim to go on ;)

**Comment by dreampiggy** [comment]
# Current break change (Need change code)

### SDWebImageManager.h
+ `transformedImageWithImage:forKey:` REMOVED, use `transformer` property instead.

**Comment by dreampiggy** [comment]
😅 Seems no one review this...

This PR can be split two parts. The first part is the interface and protocol for `SDWebImageTransformer`, which allow user to transform current `UIImage` to another `UIImage`. The `cacheKey` is provided for the context of current image.

The second part is the `UIImage+Transform` category, which provide some common image processing util and the code is from popular lib such as UIImageAddtions and YYCategory. We just make it more easy to use and add macOS support. There are tests for keeping these method work.

To keep the 5.x milestone at date, maybe this PR should be merged in weeks. Any idea ? @mythodeia @skyline75489

**Comment by skyline75489** [comment]
I'm a little bit worried that `UIImage+Transform` interface would change a lot in the future. Should it really be exposed to users anyway?

**Comment by dreampiggy** [comment]
@skyline75489 Well...Why we need this because maybe we can make it easy to use for common usage and normal user. But this keep the extensibility to let you provide a total custom transfomer. I think our library can aim to easy-to-use for beginning user(Actually most user are these type :)), but also allow advanced user to customize.

These code actually are reference from other image process lib such as [UIImage-Additions](https://github.com/vilanovi/UIImage-Additions), if user need more feature, just build their own, it's really simple and easy, so don't need to change the API again and again.

But anyway, if you think some of these common transformer's API can be polished, you can comment here.

**Comment by skyline75489** [comment]
What I'm saying is that we are using methods in `UIImage+Transform` inside the library. At the same time it's exposed to user. If some day we'd like to change those, we'll be having a hard time doing that since some users may also use them.

Take our lib YTKNetwork for example. We intentionally make our util class private (https://github.com/yuantiku/YTKNetwork/blob/master/YTKNetwork/YTKNetworkPrivate.h) so that we can change it without breaking other people's code.

**Comment by dreampiggy** [comment]
@skyline75489 These `UIImage+Transform` category are designed to be exposed to the user. Especially the beginner user for common image processing(Well, static image only).

Why to introduce this may because of our friend [Kingfisher](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#built-in-processors-of-kingfisher), which provide some build-in transformer, as well as the [UIImage category](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#useful-image-extensions) which called by transformer.

I think this design is not bad, for image transformer, most cases it's a non-business related stuff and common usage, which means everyone can write the same code when implement it (like you write a sorting algorithm). So we can just provide the common function to let user use out of box. We will never do any business-related transformer, these should be done by user using custom coder.

**Comment by skyline75489** [comment]
That's cool. My other concern would be the naming. `UIColor + Additions` and `UIImage + Transform` seems to be tool general. I think it's better to prefix it with `SD`.

**Comment by dreampiggy** [comment]
@skyline75489 I found that all our previous category does not follow the prefix naming, such as `UIImage+WebCache`, `NSData+ImageContentType`. Only the category method itself does (Greate...no conflict)...So I just follow. Actually maybe we should do this :)

And, for Objective-C, the **same category name** acually does not cause serious problem, only the *same method name* does, which will replace one of the same name method during runtime. See [stackoverflow](https://stackoverflow.com/questions/5689088/do-objective-c-category-names-do-anything)

**Comment by dreampiggy** [comment]
@skyline75489 I move those two `UIColor+Addtions` and `NSBezierPath+Addtions` category into the implementation files and change the category name. This can avoid any name conflict.

For that `UIImage+Transform.h` category naming, I think it's adoptable and I search the cococapods, there are no same naming category. Since Objective-C category name does not do anything, if user have meet some category naming (not method name) warning, they can just ignore it. Or they can using the full path header like `#import <SDWebImage/UIImage+Transform.h>` to mark with `-Weverything` around.

**Comment by dreampiggy** [comment]
Merged. Since this can be a independent component between manager. We can maintain this without change so much core API.

**Comment by bpoplauschi** [comment]
@dreampiggy about this PR:
- I appreciate your work here, properly describing the issue, the design and the implementation
- but in my opinion, some of this code does not belong in this library/module and we should not maintain it. Code like applying `CIFilter`s or rounding corners of images. I see `SDWebImage` as a well defined module that does image download and cache and not more. We could have created modules on top that can be brought in by the people who need them.
- this has multiple reasons, among which the need for the code to be minimal, so it's easy to review for us and for the users, to maintain and to understand.
- BUT, since this is a joint effort of maintaining the library, the other active contributors @skyline75489  and @mythodeia didn't disagree and that I was silent while this PR was developed, I will not try to convince you to change it. Let's see how this goes.

**Comment by bpoplauschi** [comment]
PS: I like the `SDWebImageTransformer` and the ways to compose transformers

**Pull request merged**
