### PR TITLE
SDImageCacheAccessedDate

### PR DESCRIPTION
**Pull request by LukeDurrant**
Added the ability to clear cache by last accessed date not by creation date
setCacheClearBy:SDImageCacheAccessedDate

### CODE REVIEW

**Comment by danielgalasko** [comment]
An update on this would be great, really keen to use a feature like this as it definitely makes more sense to use an LRU disk cache than date added... (at least in our case)

**Comment by mythodeia** [comment]
based on this [this](http://stackoverflow.com/questions/12148507/files-accessdate-not-altered-after-reading-the-file-by-nsdata-datawithcontents) ```NSURLContentAccessDateKey``` is not set with every read access of the file

**Comment by mvoong** [comment]
@LukeDurrant did you have a chance to confirm?

**Comment by bpoplauschi** [comment]
@LukeDurrant can you please respond to this thread?

**Comment by LukeDurrant** [comment]
This worked in 2014.
Not sure if it does now.

**Comment by paulosaure** [comment]
Hello,

I'm back to the subject but I would like to know why this pull request has never been merged ? 
I checked in `SDImageCache.m` file (v4.3.3) and we still can not use `NSURLContentAccessDateKey` :(

**Pull request closed without merging**
