### PR TITLE
Support caching of png transformation

### LINKED ISSUE #815: transformation of image not saved after restore from cache
If save transformed image (flipped) to cache:
`UIImage* flippedImage = [UIImage imageWithCGImage:sourceImage.CGImage
                                                    scale:sourceImage.scale
                                              orientation:UIImageOrientationUpMirrored];`
then it will be still flipped if get from memory, but not flipped when get from disk.

### PR DESCRIPTION
**Pull request by ivangolub**
This is small fix to resolve #815

### CODE REVIEW

**Comment by bpoplauschi** [comment]
I must say I don't really understand how is this caching anything. Could you add some details, maybe some links with the explanation on those changes?

**Comment by ivangolub** [comment]
Hi @bpoplauschi its been a long time since I made this PR 😄 
The idea was to keep EXIF data of png image, including transformations and other stuff, which was apparently lost if use ```UIImagePNGRepresentation```. Unfortunately I didnt find any apple doc proof, just few SO links on related topic: [here](http://stackoverflow.com/questions/15239719/convert-uiimage-to-nsdata-without-using-uiimagepngrepresentation-or-uiimagejpegr), [here](http://stackoverflow.com/questions/3554244/uiimagepngrepresentation-issues-images-rotated-by-90-degrees) or [opposite goal](http://stackoverflow.com/questions/25589118/stripping-all-exif-data-in-objective-c)
I had this issue in one of my projects back in 2014, and its is not relevant for me anymore. Unfortunately I cant test current SDWebImage version to check how it behaves right now, so its absolutely up to you if you want to have this code in or not.
Thx for your time and effort.

**Comment by bpoplauschi** [comment]
@ivangolub I appreciate the response and sorry it didn't go in at that time. For now, it sounds safer just to close this PR

**Comment by bpoplauschi** [comment]
I think this one is now fixed by #2034

**Pull request closed without merging**
