### PR TITLE
set placeholer even if the url is nil

### PR DESCRIPTION
**Pull request by baight**

### CODE REVIEW

**Comment by bpoplauschi** [comment]
Not sure if this is the desired behavior. I will not merge this for now, but appreciate the work @baight

**Comment by baight** [comment]
But why UIImageView+Webcache has setted the placeholder when the url is nil.
At least, I think UIButton+Webcache and UIImageView+Webcache should have the same behavior, isn't it ? @bpoplauschi

**Comment by bpoplauschi** [comment]
@baight they should behave in the same way, even though people got used to this behaviour. Let's revisit this

**Comment by dreampiggy** [comment]
Merged with #2043

**Pull request closed without merging**
