### PR TITLE
Replace runningOperations of SDWebImageManager from Array to Set

### PR DESCRIPTION
**Pull request by zhongwuzw**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [ ] I have added the required tests to prove the fix/feature I am adding
* [ ] I have updated the documentation (if necessary)
* [ ] I have run the tests and they pass
* [ ] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / reffers to the following issues: ...

### Pull Request Description

Reason:
We need to remove operation, so let's replace it with `NSSet`.

### CODE REVIEW

**Comment by dreampiggy** [comment]
@zhongwuzw I'm a little wonrdered about this change. Does that we use a Array because of some histroical reason ?

The different between `NSSet` and `NSArray` for the value, may be that the object `isEqual:` and `hash` method. `NSSet` does not check `isEqual:` but only use `hash` instead. Is that the collection previouslly can store a outside object which may subclass and provide a custom implementation of this (Which may not check ?

If not, maybe this change is adoptable. I'm not be opposed to this change, just a little curious about it. 😅

**Comment by zhongwuzw** [comment]
@dreampiggy It's a long story. 😢 6 years ago, [this commit](https://github.com/rs/SDWebImage/commit/2227266c41c65f55d1e7f9a37ca2a30325689658) introduced `failedURLs` and `runningOperations `, they were all `NSMutableArray`. 3 years ago, `ikesyo` commit a `PR` to change `failedURLS` to `Set`, See [commit](https://github.com/rs/SDWebImage/pull/1076/files).

`runningOperations` only uses internal and store `SDWebImageCombinedOperation`. So I think it's ok to use `Set`.

Actually, `NSSet` still needs to implement `isEqual`, if multiple objects put in the same bucket, `Set` would use `isEqual` to figure out. That is to say, `isEqual` and `hash` are the couple. 😄

**Comment by bpoplauschi** [comment]
@zhongwuzw as a global rule, I kindly ask you (and the other contributors) not to merge our own PR's. I know in this case I had already approved the PR, but I think it's cleaner and safer that at least another member reviews any change before it's merged.
Sometimes, to move things faster, we are tempted to take shortcuts (like my case with f8fe886 committed directly on the 5.x branch), so we need each other to remind us we can do better :)

**Comment by zhongwuzw** [comment]
@bpoplauschi 👌 I'll be careful next time. 😂

**Comment by dreampiggy** [comment]
......@bpoplauschi This change...Acutally will cause issue. Since `SDWebImageCompat.h` it's a public header in all files. If user have their own global define for this, this will cause compile failed. (Like some code in our company's codebase).


I think, it's time now (I'm really amazed that previous version does not have this one) to define a private header which should not expose to any files outside our framework. We can use `private_header_files` in CocoaPods/(Xcode's private header files) to manage it. Put all the private define or category inside it.

I can create one for this... :)

**Comment by bpoplauschi** [comment]
@dreampiggy the ideal solution is a private header, but that's a bit complicated (with Carthage and CocoaPods and all). I would just prefix to `SD_LOCK`

**Comment by dreampiggy** [comment]
@bpoplauschi Cocoapods can use that `private_header_files` in Podspec. Carthage / Xcode manual install way can use Xcode's built-in **Target Membership** option to change the define to `private` to avoid this...This seems works well for both of this...

**Pull request merged**
