### PR TITLE
fix 'nullable' to 'nonull'

### PR DESCRIPTION
**Pull request by AaronZhang2015**
### New Pull Request Checklist

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [ ] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [ ] I have added the required tests to prove the fix/feature I am adding
* [ ] I have updated the documentation (if necessary)
* [ ] I have run the tests and they pass
* [ ] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / reffers to the following issues: ...

### Pull Request Description

...

### CODE REVIEW

**Comment by dreampiggy** [comment]
LGTM. But I'm wondering this is a API-break change(Options and Non-optional is different case). Anyway, I advice to merge this to 4.3. @Baichenghui @skyline75489 What the idae.

**Comment by skyline75489** [comment]
I'd also say 5.x is better.

**Comment by dreampiggy** [comment]
@skyline75489 Any reason ?

**Comment by skyline75489** [comment]
I think we should leave all API changes to 5.x.

**Comment by mythodeia** [comment]
i agree with @skyline75489. Looks good but maybe it will be better to add this to 5.x ?

**Comment by dreampiggy** [comment]
@AaronZhang2015 This nullability change is correct. For Objective-C, this will not break API, but for Swift, this may(actually you can pass it an nil because that the runtime assert will trigger) break API. So we should merge this into 5.x.

Don't worry, 5.x seems to be not a big API-break change and it's easy to migrate(Unlike 3.x->4.x). Thanks for you contribution :)

**Pull request merged**
