### PR TITLE
Allowing clients to pull out frame duration data for WebP

### PR DESCRIPTION
**Pull request by Pearapps**
Adds hooks into the webp coder to get raw frames and not the UIImage type

### CODE REVIEW

**Comment by dreampiggy** [comment]
Well. I talk about this in previous PR. This new public API is useless for SDWebImage framework. Because our inner procedure do not need this `framesWithData:` method during image downloading ,decoding and caching. So it should be treated as own user's own business logic. So I advice not to merge this into our repo.

In fact, you can easily build this custom coder. Just create your own category or subclass.  You can try these code:

```objectivec
@class SDWebImageFrame;
@interface SDWebImageWebPCoder (FrameProcess)

- (nullable NSArray <SDWebImageFrame *> *)framesWithData:(nullable NSData *)data;

@end

@implementation SDWebImageWebPCoder (FrameProcess)

- (NSArray<SDWebImageFrame *> *)framesWithData:(NSData *)data {
    UIImage *animatedImage = [self decodedImageWithData:data];
    if (!animatedImage) {
        return nil;
    }
    return [SDWebImageCoderHelper framesFromAnimatedImage:animatedImage];
}

@end
```

**Comment by Pearapps** [comment]
That code will still use the GCD method that we do not desire

**Comment by dreampiggy** [comment]
@Pearapps ? You mean `framesFromAnimatedImage:` ? This unapply the gcd frame patch for the UIImage. See the description:

```
/**
 Return frames array from an animated image.
 For UIKit, this will unapply the patch for the description above and then create frames array. This will also work for normal animated UIImage.
 For AppKit, NSImage does not support animates other than GIF. This will try to decode the GIF imageRep and then create frames array.

 @param animatedImage A animated image. If it's not animated, return nil
 @return The frames array
 */
```

**Comment by dreampiggy** [comment]
Maybe that document comments is a little misunderstanding? Need to add extra documents or wiki for this. 😅

**Pull request closed without merging**
