### PR TITLE
Adds support for iOS 8+ Framework and Carthage

### PR DESCRIPTION
**Pull request by flovilmart**

### CODE REVIEW

**Comment by rromanchuk** [comment]
:+1:

**Comment by bpoplauschi** [comment]
@flovilmart we definitely want Carthage support, I will review this soon and reply.

**Comment by flovilmart** [comment]
@bpoplauschi : There are some problems with the Travis CI build, but no tests failed.

The framework is not tested against the test suite, but that should be easy to implement with a simple processor macro to test against the framework instead of the static lib.

Do you want me to check that?

**Comment by rromanchuk** [comment]
@flovilmart i also checked out this branch and gave it a test, working fine

**Comment by flovilmart** [comment]
@rromanchuk it's working fine, it's in production in an app now :)

**Comment by flovilmart** [comment]
@bpoplauschi Looks like adding the WebImage scheme to the workspace did the trick

**Comment by bpoplauschi** [comment]
Great work. Thanks @flovilmart

**Comment by flovilmart** [comment]
@bpoplauschi NP :)

**Pull request merged**
