### PR TITLE
Fixed issue where animated image arrays could be populated out of order

### PR DESCRIPTION
**Pull request by sean9keenan**
Assumes that calls to sd_setAnimationImagesWithURLs should create an animation image that is always in the same order as the array specified. Currently the code populates the animation in the order that the images are returned

### CODE REVIEW

**Comment by sean9keenan** [comment]
I can also change this to use a separate data-structure to sort images when coming from the callback. But this solution seemed more elegant/space/speed efficient, and much better than what was currently there. The only disadvantage to the way it's implemented is that images that are returned out of order can be displayed on the screen for longer than they should be until the image that was supposed to return before it is returned. Let me know if you have any feedback! :smile:

**Comment by sean9keenan** [comment]
@bpoplauschi - Not sure if you're the best person to look over this change. I'd really appreciate it!

**Comment by bpoplauschi** [comment]
I understand the issue but I'm not sure your fix is right.
You keep adding the image to that array
```
while ([currentImages count] < idx) {
  [currentImages addObject:image];
}
currentImages[idx] = image;
```

**Comment by sean9keenan** [comment]
The loop should only execute when the images are out of order.
eg if the images (1 indexed) are returned in the order : 1, 4, 3, 2
[1] -> [1, 4, 4, 4] -> [1, 4, 3, 4] -> [1, 2, 3, 4]

In order to have the array construct itself like this
[1] -> [1, 4] -> [1, 3, 4] -> [1, 2, 3, 4] 
it would require a separate data-structure, which I could change it to, but in practice doesn't seem to make much of a difference.

I also have been using this change for a few months now and haven't seen any issues. Thanks for taking a look at it!

**Comment by bpoplauschi** [comment]
Sounds right. I'm not sure if it would be better to fill the array with the same image or an empty image.

**Comment by sean9keenan** [comment]
The reason I picked the same image was so that something that roughly belongs in the gif (in approximately the right location) would be visible (although for longer than expected), instead of a gap in the playback - which I expect would look more jarring. I also didn't see any harm in using the same image since they should just be pointer references to the image - and not full copy's

**Comment by sean9keenan** [comment]
Just wanted to bump this PR - If it counts for anything we've been using this modification (in the form of a category that only overrides this one function in SDWebImage) for over a year in production now.

**Comment by bpoplauschi** [comment]
Ok @sean9keenan. Rebase and I will look into merging it.

**Comment by sean9keenan** [comment]
Gone ahead and rebased 👍

**Comment by bpoplauschi** [comment]
Ok let's give this a try in prod - merging.

**Pull request merged**
