### PR TITLE
removing 'and' from method names

### PR DESCRIPTION
**Pull request by Coeur**
Following Coding Guidelines for Cocoa from Apple: https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/CodingGuidelines/Articles/NamingMethods.html

### CODE REVIEW

**Comment by bpoplauschi** [comment]
Good point, but I will merge this PR into the 4.0 branch, as we might still want to release a 3.x version and this change will make it loose backwards compatibility.

**Comment by AndyZhaoHe** [comment]
ok

**Comment by Coeur** [comment]
I've kept the old names as deprecated methods: there won't be issue with backwards compatibility

**Comment by bpoplauschi** [comment]
Replaced by 5b05d6c

**Pull request closed without merging**
