### PR TITLE
Additional http headers

### PR DESCRIPTION
**Pull request by BlueVirusX**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have added the required tests to prove the fix/feature I am adding
* [x] I have updated the documentation (if necessary)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / reffers to the following issues:
#232 
#729
#166 

### Pull Request Description

This PR should solve the problem when every HTTP request needs different HTTP headers.
Now it is possible to set a dictionary of additional HTTP headers per request and the completion block provides access to the response headers.

### CODE REVIEW

**Comment by dreampiggy** [comment]
Any idea about using `SDWebImageDownloaderHeadersFilterBlock` in `SDWebImageDownload.sharedDownloader` ? 

And also , change this **OPEN API** will break current user's code, please consider carefully or find another way to approche this feature.

**Comment by BlueVirusX** [comment]
First I thought that using `SDWebImageDownloaderHeadersFilterBlock` might work, but in my case I need to set different header values for each request and I need the returned headers from the response. So using `SDWebImageDownloaderHeadersFilterBlock` isn't working for my case.

To avoid breaking API changes I can add public methods without the `additionalHeaders` parameter.

But I am not sure about the `SDInternalCompletionBlock`:
To get access to the response headers I have to add it as block parameter, but this will break `-[SDWebImageManager loadImageWithURL:options:progress:completed]`.
But adding another `SDInternalCompletionBlock` like
`typedef void(^SDInternalCompletionWithHeadersBlock)(UIImage * _Nullable image, NSData * _Nullable data, SDHTTPHeadersDictionary * _Nullable responseHeaders, NSError * _Nullable error, SDImageCacheType cacheType, BOOL finished, NSURL * _Nullable imageURL);`
might be confusing?

**Comment by dreampiggy** [comment]
@BlueVirusX If you need all information about HTTP response, I think it's not recommended to use `SDWebImageDownloader` because it's made for simplicity and focus on **common usage** for image downloading but not an full-stack network framework.

Instead, you can use `NSURLSession` or some network framework like `AFNetworking` for HTTP request, in the completion block , use that `UIImage+MultiFormat` category method or `FLAnimatedImage`(For GIF) to decode NSData to UIImage, add you can easily grab HTTP Reponse header then use this information in your bussness logic. 

If we all want more complicated information like statusCode, redirect URL(since HTTP supports redirect), MIME Type(although we have SDWebImageFormat, but what if I want do custom decoding for unsupported format?). This API design will all failed. I think this should be an further discussion, any idea? 😃

**Comment by BlueVirusX** [comment]
I understand your arguments against adding more HTTP request/response related because this will bloat the API. But I though sharing these additions with other users of your API would be a good idea, because others requested this feature too.

Maybe someone else can join the discussion and share his/her opinion on adding this to the API or have some better ideas about HTTP headers.

Maybe it's worth it 👍

**Comment by BlueVirusX** [comment]
By the way I have removed all breaking changes in public API except this interface:
`-[SDWebImageDownloaderOperationInterface addHandlersForProgress:completed:]`
`-[SDWebImageDownloaderOperation addHandlersForProgress:completed:]`

**Comment by dreampiggy** [comment]
@BlueVirusX I think your use case is adoptable, but this is really rare. I think we can provide a way for this by not change too more public API. See my solution.

First, for your use case `set different header values for each reques`, you can done this by provide a `SDWebImageExternalAddtionalHeadersKey` in `UIView+WebCache` actegory. The value of this key is a `NSDictionary<NSString*,NSString*>`. 

Then, this value is passed to `SDWebImageDownloader`. We need introduce a same `context` arguments to pass it and let downloader create a acutal `NSURLRequest` with it. Then all things done.

---

Second, for your use case `need the returned headers from the response`, this means we should have a way to grab the `NSURLResponse`. However, currently we have no way. But there is a `SDWebImageDownloadToken`. We put this `NSURLResponse` into `SDWebImageDownloadToken`, then pass this to top.

We have a `UIView+WebCacheOperation` category, which seems a good place to put it because we bind a `SDWebImageOperation` to UIView. We just need to add a new property such as`token` for this and you can now grab the `NSURLResponse`.

I can write a PR to show how to combine all these together.

**Comment by dreampiggy** [comment]
@BlueVirusX See #2166

**Comment by BlueVirusX** [comment]
I really like your approach in #2166 👍 
Is it possible to add the download token to the operation returned by `-[SDWebImageManger loadImageWithURL:options:progress:completed:context:]`?

Like this:
```
@interface SDWebImageCombinedOperation : NSObject <SDWebImageOperation>
...
@property (strong, nonatomic, nullable) SDWebImageDownloadToken *downloadToken;

@end
```
And set it here:
```
- (id <SDWebImageOperation>)loadImageWithURL:(nullable NSURL *)url
                                     options:(SDWebImageOptions)options
                                    progress:(nullable SDWebImageDownloaderProgressBlock)progressBlock
                                   completed:(nullable SDInternalCompletionBlock)completedBlock
                                     context:(nullable SDWebImageContext *)context {
...
operation.downloadToken = [self.imageDownloader downloadImageWithURL:url options:downloaderOptions progress:progressBlock completed:^(UIImage *downloadedImage, NSData *downloadedData, NSError *error, BOOL finished) {
...
```
Then it would be possible to access the `NSURLResponse` when using the `SDWebImageManger` instead of the `SDWebImageDownloader`.

**Comment by dreampiggy** [comment]
@BlueVirusX We can add that `SDWebImageDownloadToken` to the `SDWebImageCombinedOperation`, but the question is that :

```objective-c
- (id <SDWebImageOperation>)loadImageWithURL:(nullable NSURL *)url
                                     options:(SDWebImageOptions)options
                                    progress:(nullable SDWebImageDownloaderProgressBlock)progressBlock
                                   completed:(nullable SDInternalCompletionBlock)completedBlock
                                     context:(nullable SDWebImageContext *)context;
```
This return type is `id<SDWebImageOperation>` but not `SDWebImageCombinedOperation`. So if you really want to do this stuff, you should write some trick code:

```objective-c
        UIImageView *imageView;

        [imageView sd_internalSetImageWithURL:[NSURL URLWithString:self.objects[indexPath.row]] placeholderImage:placeholderImage options:0 operationKey:nil setImageBlock:nil progress:nil completed:^(UIImage * _Nullable image, NSError * _Nullable error, SDImageCacheType cacheType, NSURL * _Nullable imageURL) {
            if (!error && cacheType == SDImageCacheTypeNone) {
                NSObject<SDWebImageOperation> *operation = [imageView sd_imageLoadOperationForKey:NSStringFromClass([imageView class])];
                SDWebImageDownloadToken *token = [operation valueForKey:@"downloadToken"];
                NSURLResponse *response = token.response;
                if ([response isKindOfClass:[NSHTTPURLResponse class]]) {
                    NSDictionary *headers = ((NSHTTPURLResponse *)response).allHeaderFields;
                    NSLog(@"%@", headers);
                }
            }
        } context:@{SDWebImageExternalAddtionalHTTPHeadersKey: @{@"foo" : @"bar"}}];
```

**Comment by dreampiggy** [comment]
Well. After some consideration, I think we should break the API and change the return type. This change should at lease in 5.x. The reason why to change this is blow here :

Our previous API `-[SDWebImageManager loadImageWithURL:options:progress:completed:]` describe that
>  @return Returns an NSObject conforming to SDWebImageOperation. Should be an instance of SDWebImageDownloaderOperation

So this is adoptable and may not break current usage. And I think, this protocol is really useless. We can make it open to the user to provide more custom advanced usage(Including your HTTP headers usage).

Compared to Kingfisher's same API[KingfisherManager.retrieveImage](https://github.com/onevcat/Kingfisher/blob/master/Sources/KingfisherManager.swift#L113), I think we should basically add two property, one is `NSOperation *cacheOperation`, the other is `SDWebImageDownloadToken *downloadToken`. Some advanced feature can be implementation and make it more user-customizable.

All the other properties should be hidden because it rely on the complex internal logic. I think now you can do something easy with it :)

**Comment by dreampiggy** [comment]
#2261 Merged. Which introduce the request modifier and expose the cache/download operation protocol, which allow you to grab back the response. So this PR can be closed.

**Comment by bpoplauschi** [comment]
@BlueVirusX We would like to invite you to become a maintainer – no pressure to accept! At this point we are only a handful of people doing this in our spare time. 
I am working on writing down the expectations from contributors, but basically

> we want contributors to provide ideas, keep the ship shipping and to take some of the load from others. It is non-obligatory; we’re here to get things done in an enjoyable way. 

Pitch in with what seems comfortable: comment on open issues/PRs, triage, improve documentation, write your own PRs.
Let us know.

Quote from [Moya Contributing guide](https://github.com/Moya/Moya/blob/master/Contributing.md#our-expectations-on-you-as-a-contributor).

**Comment by BlueVirusX** [comment]
@bpoplauschi Thanks for your invite! I would be glad if I could help you.
From November to December I'm quite busy, but maybe I can work some basic tasks like PR reviews, documentation.

**Comment by bpoplauschi** [comment]
Sounds good @BlueVirusX. I have sent you an invite to the organization

**Pull request closed without merging**
