### PR TITLE
Allow to customise cache and image downloader instances used with SDWebImageManager

### PR DESCRIPTION
**Pull request by zats**
I was looking around the library to see if there is a way to have "buckets" of cache to allow easier disposal of a particular bucket. 
For example, imagine you have a bunch of resources that should outlive the app lifecycle and bunch that are relatively temporary: (let's say you want to dispose them every time you leave a particular screen).
From my limited investigation, I couldn't find anything that would allow to implement this.
As a quick ad-hoc solution, I thought of allowing to specify `SDImageCache` and `SDWebImageDownloader` instances when constructing `SDWebImageManager`.
This way you can have something similar to this (sorry for Swift):
```swift
struct ImageCache {
  static let longLeavingCache = SDWebImageManager(cache: onDiskCache, downloader: sharedDownloader)
  static let newsfeedCache = SDWebImageManager(cache: temporaryCache, downloader: fastDownloader)
}
```
This would allow to:
* Choose appropriate downloader for particular use case;
* Dispose cache as needed (if you prefer not to keep particular data on the disk longer then necessary)
* Extend lifecycle of a particular cache by placing it outside of the `<AppContainer>/Library/Caches/`

### CODE REVIEW

**Comment by zats** [comment]
hey, wanted to ping to see if there is anything I can do to improve this PR?

**Comment by bpoplauschi** [comment]
I see your point and is valid. But I don't think the extra `manager` param on the UIKit categories methods makes sense. If you go down your road, you could always use the `SDWebImageManager` layer.

**Comment by bpoplauschi** [comment]
@zats I added the 1st part of your work in 86fc47bf7b80bdfea49d39d9ad4d719bba90015c. Hope this helps.

**Comment by zats** [comment]
thank you!

**Comment by zats** [comment]
hi @bpoplauschi, I checked your solution again and it seems like I'd need to reimplement entire UIKit layer on top of the manager. 
```
- (void)sd_setImageWithURL:(NSURL *)url placeholderImage:(UIImage *)placeholder options:(SDWebImageOptions)options manager:(SDWebImageManager *)manager progress:(SDWebImageDownloaderProgressBlock)progressBlock completed:(SDWebImageCompletionBlock)completedBlock {
```
provides a lot of additional functionality I would want to avoid of implementing. Or am I missing another, less involved solution using `SDWebImageManager`?

**Comment by zats** [comment]
I'm trying to understand your reasoning against being able to configure `UIImageView` with a particular instance of `SDWebImageManager` - seems like an optional parameter that doesn't affect any of existent code

**Comment by bpoplauschi** [comment]
It would require too many changes. The current design of the library is built on a singe manager instance and this cannot change very easily. I think you should just fork (if you haven't already) and use your version for what you need it.

**Pull request closed without merging**
