### PR TITLE
[IOCoder] Avoid using `animatedImageWithImages:duration:` for a GIF image

### PR DESCRIPTION
**Pull request by ikesyo**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [ ] ~~I have added the required tests to prove the fix/feature I am adding~~
* [ ] ~~I have updated the documentation (if necessary)~~
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / reffers to the following issues: https://github.com/rs/SDWebImage/issues/1732#issuecomment-356193885

May be related to #2155.

### Pull Request Description

Looks like that is problematic for `UIButton` integration.

### CODE REVIEW

**Comment by dreampiggy** [comment]
To say. I already know this, your change will cause `FLAnimatedImageView` logic failed. Because some trick logic(Such as request disk cache synchronized) is checked with `image.images != nil`.

This behavior will be totally removed during SD 5.x. Currently we have no good way to avoid it(without modify any header files).

**Comment by dreampiggy** [comment]
And to say, what's the problem for using `_UIAnimatedImage` for `UIButton` ? I tested it and it works as normal static `UIImage`.

**Comment by dreampiggy** [comment]
@ikesyo I'm working fine. Simply add a UIButton subview on our demo:

```objective-c
@interface MyCustomTableViewCell : UITableViewCell

@property (nonatomic, strong) UILabel *customTextLabel;
@property (nonatomic, strong) FLAnimatedImageView *customImageView;
@property (nonatomic, strong) UIButton *customButton;

@end

//initWithStyle:reuseIdentifier
_customButton = [[UIButton alloc] initWithFrame:CGRectMake(300.0, 2.0, 60.0, 40.0)];
[self.contentView addSubview:_customButton];

//tableView:cellForRowAtIndexPath:
    [cell.customButton sd_setImageWithURL:[NSURL URLWithString:self.objects[indexPath.row]] forState:UIControlStateNormal placeholderImage:placeholderImage options:0];
```

simulator screen shot - iphone 7 - 2018-01-09 at 17 39 59


Could you provide your use case ? Maybe it's not the issue related to `_UIAnimatedImage` because I think it's UIKit's native methods and it should work as normal `UIImageView`

**Comment by ikesyo** [comment]
> And to say, what's the problem for using _UIAnimatedImage for UIButton ? I tested it and it works as normal static UIImage.

I'm not sure why but when a cell is reused the button's image view is empty (cleared). I'm working around this with the following:

```swift
button.sd_setImage(with: url, for: state, placeholderImage: nil, options: [ .avoidAutoSetImage ]) { image, _, _, _ in
    let image = image?.images?.first ?? image
    self.button.setImage(image, for: state)
}

```

**Comment by ikesyo** [comment]
Anyway closing this for now. Thanks for the response!

**Comment by dreampiggy** [comment]
@ikesyo Could you please provide a demo ? I think this maybe something related to rare case but not `_UIAnimatedImage` itself because I have a UIButton showing animated images in my application...

Maybe it's a UIKit bug, but we need more information about this.

**Comment by dreampiggy** [comment]
@ikesyo I can pick some 5.x code to 4.x branch, see. This can disable that tricky logic for `FLAnimatedImage` and make `SDWebImageIOCoder` works without any animated image.

See #2162

**Comment by dreampiggy** [comment]
Fixed by #2162

**Pull request closed without merging**
