### PR TITLE
Fixed SDWebImageOperation cancelling

### LINKED ISSUE #847: -downloadImageWithURL:options:progress:completed: completion block not called in some cases
Not sure what's causing it, but:      

    - (id <SDWebImageOperation>)downloadImageWithURL:(NSURL *)url
                                     options:(SDWebImageOptions)options
                                    progress:(SDWebImageDownloaderProgressBlock)progressBlock
                                   completed:(SDWebImageCompletionWithFinishedBlock)completedBlock;

is sometimes not calling the completion handler. This problem surfaced when updating from *SDWebImage* 3.6 to 3.7.1, but not sure which particular code change caused to make it happen.

We are heavily using the `SDWebImagePrefetcher` in parallel to the aforementioned method.

See #781 for my initial report.

### PR DESCRIPTION
**Pull request by timkoma**
1.
Fixes #847 #1030 #1032 #1034:
Problem description:
If you will set the same URL to 2 different UIImageViews, only one download operation is started(for the first one). 
If the first one gets cancelled because of setting the new URL(possible with UICollectionView recycled views during scrolling), 
second will never load any image and will never be notified about cancel.

2.
Call UIImageView's progressBlock on main thread - otherwise you can get crash when UIKit's objects deallocation will happen in background thread

3.
Included Pull request #1044 (Fixes#990)

### CODE REVIEW

**Comment by timkoma** [comment]
@rs, @bpoplauschi 
There is a problem with WebP. I do not know how to fix it:

 -> SDWebImage (3.7.2)
    - WARN  | [iOS] [SDWebImage/WebP]  libwebp/src/utils/bit_writer.c:262:11: warning: code will never be executed [-Wunreachable-code]
    - NOTE  | [iOS] [SDWebImage/WebP]  libwebp/src/utils/bit_writer.c:261:29: note: silence by adding parentheses to mark code as explicitly dead
[!] SDWebImage did not pass validation.
You can use the `--no-clean` option to inspect any issue.
The command "pod lib lint" exited with 1.

**Comment by bpoplauschi** [comment]
The problem with WebP is that the `bit_writer.c` file generates a warning because of some unused code. I've fixed Travis by adding the `--allow-warnings` flag to `pod spec lint`. Please rebase on top of master

**Comment by timkoma** [comment]
Thanks, now The Travis CI build passed.

**Comment by timkoma** [comment]
Sorry for the late response, I'm busy right now, I will take a look at this next week.

**Comment by philipengberg** [comment]
How is this pull request coming @timkoma?

**Comment by timkoma** [comment]
@theprojectabot  - I had no crash

**Comment by LeffelMania** [comment]
What's the status of this request? I'm seeing this issue quite a bit in my table views, and seems like a generally pretty important fix to incorporate.

**Comment by philipengberg** [comment]
What is the status? @timkoma

**Comment by timkoma** [comment]
still haven't been merged. 
@mythodeia @bpoplauschi are you planning to merge it ?

**Comment by mythodeia** [comment]
@timkoma i remember i tried your code and i had some issue when several urls where not downloading at all while scrolling.

**Comment by timkoma** [comment]
@mythodeia do you have a demo how to repro? I wasn't aware of the any issues.

**Comment by mythodeia** [comment]
@timkoma no i do not have anything as all my tests were made in a private app i was working. 
What you could do, if you have some free time, is to cleanup all the commits here and rebase into a new pull request so we can retry it as these changes here are not easily debugged/checked.

**Comment by bpoplauschi** [comment]
@timkoma why did you close the PR? I just started re-reviewing it yesterday :)

**Comment by timkoma** [comment]
I though that you are not planning to merge it :)

**Comment by bpoplauschi** [comment]
It took a lot, but I am looking at it. Trying to comprehend all the underlying changes - not easy :)

**Comment by bpoplauschi** [comment]
In the meantime, it would help me if you could do a merge from master into this branch, or at least review the one I did and pushed it to my fork: https://github.com/bpoplauschi/SDWebImage/tree/SDWebImageOperation+Canceling

**Comment by timkoma** [comment]
I can try to merge from master...

**Comment by timkoma** [comment]
@bpoplauschi merged with master

**Comment by bpoplauschi** [comment]
Great @timkoma

**Comment by timkoma** [comment]
@bpoplauschi how it is going? Still comparing with #883?
 Is there anything I can help with?

**Comment by bpoplauschi** [comment]
@timkoma I kept getting interrupted and wasn't able to finish this, but I am getting back to this library.

**Comment by bpoplauschi** [comment]
After analysing this MR and #883, I think the safer one is #883, as #1069 had shown issues and failed to pass the tests from #1222. Thanks @timkoma for all your support and work here, but for now I will go with the other implementation. Hope I am making the right decision.

**Pull request closed without merging**
