### PR TITLE
Add a options to allow query the memory cache with data synchronously, but disk cache asynchronously

### PR DESCRIPTION
**Pull request by dreampiggy**
Currently two options can not cover this use case

### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have added the required tests to prove the fix/feature I am adding
* [x] I have updated the documentation (if necessary)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / reffers to the following issues: #2216 #2162 

### Pull Request Description

It seems that during the refactory to remove the tricky code for `if (memoryImage.images) { // query disk cache sync}` in SDImageCache, we miss a use case.

At that time, we introduce two cache options to control the behavior when call `queryCacheOperationForKey:`. However, if I want this use case, I can't do this by combining the current two options:

+ Query the memory cache, if memory cache hit, query the disk cache synchronously
+ If memory cache miss, query the disk cache asynchronously

When you use `SDWebImageQueryDataWhenInMemory | SDWebImageQueryDiskSync`, however, this will cause the second one become 'If memory cache miss, query the disk cache synchronously'. So this acually does not cover this use case.

However,  this use case is the default behavior during SD 4.0 - 4.2. Though in 4.3 we change this and fix the FLAnimatedImageView rendering performance by using associated object to store the FLAnimatedImage instance into memory cache. I found recently some users still need this use case. So we should provide a way to give it back.

So now, for the use case above, I can use `SDWebImageQueryDataWhenInMemory | SDWebImageQueryDataSync` instead

### CODE REVIEW

**Comment by dreampiggy** [comment]
Actually these 3 options can control all the behavior you need, though it's little confused. Here I list the result by using these 3 options.

Options | Memory hit data | Memory miss data
-- | -- | --
0 | nil | async
QueryDiskSync | nil | sync
QueryDataWhenInMemory | async | async
QueryDataWhenInMemory + QueryDataSync | sync | async
QueryDataWhenInMemory + QueryDiskSync | async | sync
QueryDataWhenInMemory + QueryDataSync + QueryDiskSync | sync | sync

**Comment by skyline75489** [comment]
Honestly I think `QueryDataSync ` doesn't seem to belong to `SDImageCacheOptions` since you must combine it with other options for it to work. 

Perhaps a better naming would be `SDImageCacheQueryDataSyncWhenInMemory` and `SDImageCacheQueryDiskSyncWhenNotInMemory`. But this seems utterly long...

**Comment by dreampiggy** [comment]
@skyline75489 😅 Well...That naming is a little long, if I can rename again, I will change these into 3 options:

`SDImageCacheQueryMemoryData`
`SDImageCacheQueryMemoryDataSync`
`SDImageCacheQueryDiskDataSync`

But this...Actually become the public API, so maybe we can not do something with the old one. Or should we mark this to 5.x and totally change this ? 😕

**Comment by mythodeia** [comment]
i see a lot of issues regarding these options coming our way.... naming is hard

**Comment by dreampiggy** [comment]
It seems this options is no need in 4.x. I'll change the correspond one in #2195 to allow user provide cacheType instead of most options. So this PR can be closed, until someone still in 4.x and have usage for this.

**Comment by dreampiggy** [comment]
Update the wiki about this 3 options: https://github.com/SDWebImage/SDWebImage/wiki/Common-Problems#behavior-about-asyncsync-control-for-cache

**Pull request closed without merging**
