### PR TITLE
Improvement module framework

### PR DESCRIPTION
**Pull request by dreampiggy**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have added the required tests to prove the fix/feature I am adding
* [x] I have updated the documentation (if necessary)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / reffers to the following issues:

### Pull Request Description

This PR add the support for modular framework using custom `modulemap` files. This allow user in Objective-C to use the umbrella headers instead of import headers one by one (Or using the CocoaPods auto-generate headers such as `SDWebImage_umbrella-Core-GIF-WebP-MapKit.h`, which is not reliable and looks quite strange...)

So now, you can simply using this instead:

```objective-c
#import <SDWebImage/SDWebImage.h>
```

or

```objective-c
@import SDWebImage;
```

To do this, we need to provide a `modulemap` files and using `s.module_map = 'SDWebImage.modulemap'` to let Cocoapods recognize it.

And also, this PR contains a file directory level organization. Why to do this because it make our framework function more clear, and let we can easilly write `core.source_files` in Podspec files.

No function changes introduces, and this is not effected for Swift user.

### CODE REVIEW

**Comment by dreampiggy** [comment]
Well...It seems that move the directory around will cause many MR conflict. I'll only move the `WebP`, `GIF`, `MapKit` subspec into sub directory. Keep the `Core` directory flat.

**Comment by dreampiggy** [comment]
@mythodeia Because I arrange all files into 4 sub directory `Core`, `GIF`, `WebP` and `MapKit`. This will cause many conflicts...So I decide to create again to only move the `GIF`, `WebP` and `MapKit` files. 😅

**Comment by mythodeia** [comment]
so will you close this MR or update it?

**Comment by dreampiggy** [comment]
@mythodeia Update it. I revert the file movement related commits, rebase again and update this one. 😅

**Comment by mythodeia** [comment]
@dreampiggy  sorry for the confusion bu i only asked if you will close this PR because your previous comment said "i decide to create again...."

**Comment by dreampiggy** [comment]
Well..Actually this will not cause API-break. I'll process it later after other things done :)

**Comment by dreampiggy** [comment]
I can just remove this PR and create a new one instead.

This PR seems actually don't need you to write any code. Just about modify `Podfile`, provide a `modulemap` files is OK...

**Comment by dreampiggy** [comment]
OK...Now I only move the `MapKit` & `WebP` files into the sub directory. All others files keep there :)

You can now using `#import <SDWebImage/SDWebImage.h>` instead of massive headers for Objective-C user. Well, previous version can also do this, but by using the CocoaPods's generated headers `#import <SDWebImage/SDWebImage_Core_MapKit_WebP_Umbrealla_header.h>`, which is quite wired...

**Comment by bpoplauschi** [comment]
Looks very clean @dreampiggy . Good idea not to move the Core files. I will take another look after lunch and merge it.

**Comment by dreampiggy** [comment]
Forget to remove that WebP headers in `SDWebImage.h`. Done

**Comment by bpoplauschi** [comment]
I'm not sure about the following case:
- the `modulemap` is defined on the root of the `podspec`, which means it's applicable to all the subspecs
- inside the `modulemap`, we do `import SDWebImage.h` which contains imports like `MKAnnotationView+WebCache.h` or `#import <SDWebImage/UIImage+WebP.h>` which are not included in all the subspecs
- so my concern is that if you try to include just some subspecs into a project, it might have an issue.
`pod 'SDWebImage/Core'` 
- one idea would be to use `#if __has_include` for all the non-core header imports inside `SDWebImage.h`

**Comment by dreampiggy** [comment]
For each module, it should have only one `umbrella headers`. In that umbrella headers, you should import all of headers for publich APIs.

I add the thing like `#if __has_include(<SDWebImage/UIImage+WebP.h>)` to only include the valid headers if need. You can not using `#if SD_MAC`, `#if SD_WEBP` in umbrella headers. See the reason I list above.....

**Comment by bpoplauschi** [comment]
The odd thing for me is the `pod lib lint` on CI doesn't fail. And I know that command will check every subspec in a test project. So I guess it works, but I'm a bit confused about it, since it should fail

**Comment by bpoplauschi** [comment]
I've quickly looked at CocoaLumberjack where I am maintainer as well - just for a comparision
- there we have a `modulemap` file, but it's not specified via the podspec. It's just added to the list of preserved paths which are just copied over `s.preserve_paths = 'README.md', 'Classes/CocoaLumberjack.swift', 'Framework/Lumberjack/CocoaLumberjack.modulemap'`
I guess CocoaPods picks it up automatically
- look at the `modulemap`
```
framework module CocoaLumberjack {
	umbrella header "CocoaLumberjack.h"
	
	export *
	module * { export * }
	
	textual header "DDLogMacros.h"
	
	exclude header "DDLog+LOGV.h"
	exclude header "DDLegacyMacros.h"
	
	explicit module DDContextFilterLogFormatter {
		header "DDContextFilterLogFormatter.h"
		export *
	}
	
	explicit module DDDispatchQueueLogFormatter {
		header "DDDispatchQueueLogFormatter.h"
		export *
	}
	
	explicit module DDMultiFormatter {
		header "DDMultiFormatter.h"
		export *
	}
	
	explicit module DDASLLogCapture {
		header "DDASLLogCapture.h"
		export *
	}
	
	explicit module DDAbstractDatabaseLogger {
		header "DDAbstractDatabaseLogger.h"
		export *
	}
}
```

The `CocoaLumberjack.h` header contains
```objective-c
// Core
#import <CocoaLumberjack/DDLog.h>

// Main macros
#import <CocoaLumberjack/DDLogMacros.h>
#import <CocoaLumberjack/DDAssertMacros.h>

// Capture ASL
#import <CocoaLumberjack/DDASLLogCapture.h>

// Loggers
#import <CocoaLumberjack/DDTTYLogger.h>
#import <CocoaLumberjack/DDASLLogger.h>
#import <CocoaLumberjack/DDFileLogger.h>
#import <CocoaLumberjack/DDOSLogger.h>

// CLI
#if __has_include(<CocoaLumberjack/CLIColor.h>) && TARGET_OS_OSX
#import <CocoaLumberjack/CLIColor.h>
#endif
```

**Comment by bpoplauschi** [comment]
It's ok now, as I see the `has_include` pattern is used.
```#if __has_include(<SDWebImage/MKAnnotationView+WebCache.h>)
#import <SDWebImage/MKAnnotationView+WebCache.h>
#endif```

I somehow missed this change

**Comment by bpoplauschi** [comment]
Great job @dreampiggy

**Comment by dreampiggy** [comment]
That because it using [Modules- Sub Module](https://clang.llvm.org/docs/Modules.html). Which allow your to using somelike

`@import SDWebImage.GIF`.

However, this is not compatible for CocoaPods like CocoaPods subspec. We'd better keep the current design as simple.

**Pull request merged**
