### PR TITLE
Animated webP support

### PR DESCRIPTION
**Pull request by lianchengjiang**
1. add animated webP support
2. add example for animated webP

----

Animated webP is a more cool than gif and more and more people need it
I add some code for support animated webP and add an example for it。it works well

### CODE REVIEW

**Comment by findyam** [comment]
image
line 18 should be #import "libwebp/webp/mux_types.h", change it and works

**Comment by lianchengjiang** [comment]
sorry, it's my mistake, i have fix it

**Comment by bpoplauschi** [comment]
Merged via 88b025a in 4.x branch

**Comment by neworiginou** [comment]
we found that animated webp play fast than normal gif

**Pull request closed without merging**
