### PR TITLE
Added a bit more description to the way to contribute to this project.

### PR DESCRIPTION
**Pull request by bpoplauschi**
### New Pull Request Checklist

* [X] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)

I have recently came across https://opensource.guide/ a collection of guides for open source. There is awesome info here regarding open source projects, building communities, handling projects, ...

I want us to learn a lot from those other open source practitioners.
One part that immediately caught my eye is how we describe the contributions we want to this project. I think we can do a lot better (details here: https://opensource.guide/how-to-contribute/).
I made a few proposals in this PR, please add your thoughts.

@dreampiggy @mythodeia @skyline75489 @zhongwuzw

### CODE REVIEW

**Comment by dreampiggy** [comment]
Look great. I've read some part of https://opensource.guide/ in last year. But maybe I can check again now.

**Comment by zhongwuzw** [comment]
I have read the contents of site, the most impressive section for me is [Building-community](https://opensource.guide/building-community/), we can do better to attract more developers participate in😊.

**Comment by dreampiggy** [comment]
Merge now ? Or need anythinig important to be append ?

**Comment by bpoplauschi** [comment]
@dreampiggy merge it. If there are any other changes, we can make another PR.

**Pull request merged**
