### PR TITLE
- Fix issue 414

### PR DESCRIPTION
**Pull request by Jur4s**
Fix issue 414

### CODE REVIEW

**Comment by rromanchuk** [comment]
@Jur4s have you put this into production yet?

**Comment by Jur4s** [comment]
@rromanchuk  Yes, and works like a charme !

**Comment by harishkashyap** [comment]
how to reproduce this issue?

**Comment by rromanchuk** [comment]
Linking for readability #414

**Comment by harishkashyap** [comment]
@rromanchuk @Jur4s Is there any way to reproduce this or do you guys know of any demo code? I will be happy to invest some time on this as well as this is an issue thats happening for us; its mostly on iOS 7.1 but not able to reproduce.

**Comment by mingweizhang** [comment]
@harishkashyap did you reproduce it? @Jur4s fix the issue by adding a dispatch_main_sync_safe for the "start" method. But when I code like this(it's a bad code),it didn't crash with out "dispatch_main_sync_safe".
```
    dispatch_async(queue, ^{
        [[SDWebImageDownloader sharedDownloader] downloadImageWithURL:url options:0 progress:^(NSInteger receivedSize, NSInteger expectedSize) {
            NSLog(@"receivedSize:%ld expectedSize:%ld", (long)receivedSize, (long)expectedSize);
        } completed:^(UIImage *image, NSData *data, NSError *error, BOOL finished) {
            self.imageView.image = image;
        }];
    });
```
I try to reproduce the issue,but it seemed to be difficult.

**Comment by harishkashyap** [comment]
@mingweizhang No we could not. Can you reproduce the issue? If so can you advice us on how to?

**Comment by harishkashyap** [comment]
@mingweizhang try my latest and see if it still crashes. If the crash was happening to due to memory leak (strong references in recursive calls) to startPrefetchingAtIndex. @rromanchuk the latest commit might fix the issue.

**Comment by mingweizhang** [comment]
yep,I got that.well done.I will try it.thx.

**Comment by bpoplauschi** [comment]
@Jur4s I have looked at the changes in this PR and I cannot understand how this fixes the issue. The only significant change is that you're forcing the code from the operation start to run on the main thread, which I think beats the purpose of having a separate operation.

**Comment by bpoplauschi** [comment]
This code has changed a lot. I will close the PR, release 4.0.0 in the near future and we will see if the issue still exists there and address it.

**Pull request closed without merging**
