### PR TITLE
Add CocoaPods support for tvOS

### PR DESCRIPTION
**Pull request by hoseking**
This should help with #1302

### CODE REVIEW

**Comment by bpoplauschi** [comment]
Thanks @hoseking

**Comment by hoseking** [comment]
No problem.

**Comment by tiagomartinho** [comment]
I receive the following message: [!] The platform of the target `X` (tvOS 9.0) is not compatible with `SDWebImage (3.7.3)`, which does not support `tvos`.

**Comment by hoseking** [comment]
A tag has not been made with these changes yet. You need to point your pod to a specific commit, https://guides.cocoapods.org/using/the-podfile.html

**Comment by tiagomartinho** [comment]
Thanks for the help! I thought that cocoapods used the master if no version was specified in the pod file.

**Comment by hoseking** [comment]
No problem :)

**Comment by ldi13** [comment]
Hello guys !
About the tvOS support, do you know if it's possible to point on the specific commit dealing with tvOS support a podspec ?

Thank you all,

Best,

Lorenzo

**Pull request merged**
